### ISSUE TITLE
`allow_nil: true` on the find method does not work as expected.

### ISSUE THREAD

**Issue by xxx** [norman/friendly_id#1001]
Hi,

From the readme, I expect that I should be able to do something like `MyModel.friendly.find('nonexistent-slug', allow_nil: true)` and have the call return `nil` without raising an exception, but when I make this call, I instead get `Couldn't find all MyModels with 'id': (nonexistent_slug, {:allow_nil=>true}) (found 0 results, but was looking for 2)`, as if the args are being splatted into a single array of IDs to find.

`MyModel.friendly.find(id)` without `allow_nil` works as expected.

I'm wondering if this is something to do with the change in how keyword args are handled between Ruby 2 and 3.

FriendlyId: 5.4.2
Ruby: 3.1.2p20
Rails: 7.0.4

**Comment by andrewcmyk** [comment]
It's not in 5.4.2: https://github.com/norman/friendly_id/blob/master/Changelog.md

**Comment by parndt** [comment]
Apologies, this is not released yet.

**Comment by parndt** [comment]
Version 5.5.0 pushed @xxx please can you try that version? 😄

**Comment by xxx** [comment]
@parndt 5.5.0 is working great. thanks!

**Comment by dchacke** [comment]
You may want to update the Readme accordingly and prompt users to install ~> 5.5.0.

**Comment by parndt** [comment]
thanks @dchacke that's good advice 🚀 - do you happen to have any capacity to open a pull request that makes that change please? Or even if you are able to add it to #1023 ?

**Comment by dchacke** [comment]
yea done
