### ISSUE TITLE
normalize_friendly_id not working in a concern

### ISSUE THREAD

**Issue by alienxp03** [norman/friendly_id#1003]
Related to previous issue, but in a different way. Couldn't find a workaround yet at the moment. https://github.com/norman/friendly_id/issues/825

```ruby
module Sluggable
  extend ActiveSupport::Concern

  included do
    extend FriendlyId
    friendly_id :custom_method
  end

  def custom_method
    SecureRandom.urlsafe_base64(12)
  end

  def normalize_friendly_id(string)
    super
  end
end
```

For this code, `custom_method` is being called, but `normalize_friendly_id` is not.

In the previous issue, the workaround works because they're not using any custom method, or rather have the same candidate column name for each of their class. In this case, I couldn't use `friendly_id :name, use: :slugged` since not all of my tables have the column `name`.

I've to use `friendly_id :id, use: :slugged` since `id` exist in all tables but doesn't seems to be working as well.

Using friendly_id 5.5.0, Ruby 3.2.0, Rails 7.0.4

**Comment by clairity** [comment]
you should stick the `normalize_friendly_id` method inside your concern's `included` block so that it runs in the context of the model, not the concern.

**Comment by alienxp03** [comment]
Thanks. Overthinking and overlooked that part. Thanks for your help!
