### ISSUE TITLE
5.5.1 release request

### ISSUE THREAD

**Issue by iwdt** [norman/friendly_id#1017]
Hey everyone,

How about releasing a new update?

I would like to address the issue with Yard documentation generation, which has been resolved in #1006. Currently, I have to specify the commit number in the Gemfile because I am using the `yard gems` command.

I would be grateful!

**Comment by parndt** [comment]
Noted @iwdt -- currently CI is failing so I'll address that first in #1021

**Comment by parndt** [comment]
Fixed by ecfe968

**Comment by iwdt** [comment]
@parndt, thanks a lot
