### ISSUE TITLE
Curious about what to do with slashes

### ISSUE THREAD

**Issue by joemsak** [norman/friendly_id#123]
As-is, the friendly_id gem replaces slashes in titles with nothing. I'd prefer it replaced them with dashes, like it does for spaces and other characters

I've seen something about overriding the normalize method but I want to make sure I get the same exact behavior with this tweak added on top: 

\ and / => -

Thanks!

**Comment by sandric** [comment]
I afraid that its rather old issue, but I think there's more to think about @rahilsondhi argument. Lets say, as @norman pointed you should use friendly_id's scope's functionality. I'd like to, but in this case you have to load parent resource first from db. If you will argue that if I do not need to load that parent resource, then do not scope resource, than what if you need, but only in particular actions - then you have to load from db parent resource even on those actions that does not need that resource. I'd really like to have such functionality, where you can set parent resource attributes somehow, as in example from @rahilsondhi code, but also to track this attribute change on update and delete and update slug respectively.
