### ISSUE TITLE
When using Friendly_ID - can you turn off find by ID?

### ISSUE THREAD

**Issue by jamsi** [norman/friendly_id#146]
If I have

```
http://example.com/states/washington
```

Can I disable access to;

```
http://example.com/states/4323454
```

IE: page available by slug only, NOT by ID.

Any ideas?

**Comment by augustoatqounter** [comment]
What about with friendlyID 5.1 version?

**Comment by kevinhofmaenner** [comment]
@smudge thanks!

@augustoatqounter `find_by_slug!` works in 5.1

**Comment by ganbootyard** [comment]
2019 `find_by_slug` works.
