### ISSUE TITLE
Duplicate slugs add double hyphens?

### ISSUE THREAD

**Issue by davidjbeveridge** [norman/friendly_id#170]
I'm using friendly_id on BlogPosts:: eg:

``` ruby
class BlogPost < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable
  has_friendly_id :title, :use_slug => true

  validates_presence_of :title, :content

  markdownize! :content

end
```

I've noticed, however, that if I create 2 different posts w/ the same title, an extra hyphen is inserted.  Eg., with 2 posts w/ the title "Hello World", the slug for the first is 'hello-world' and the post for the second is 'hello-world--2'.

Is there any way to make the second simply be 'hello-world-2' rather than 'hello-world--2' ?

**Comment by sahil290791** [comment]
@davidjbeveridge How did you get the desired result?
