### ISSUE TITLE
WhatsNew.md file is missing

### ISSUE THREAD

**Issue by christophermanning** [norman/friendly_id#186]
The url http://rubydoc.info/github/norman/friendly_id/master/file/WhatsNew.md listed in the [README](https://github.com/norman/friendly_id/blob/master/README.md) is 404.

**Comment by boscowitch** [comment]
and 404  again ;)

**Comment by norman** [comment]
Where are you seeing that link? It's no longer referenced in the README.

**Comment by boscowitch** [comment]
Oh right it was some deprecated warning when i was updating rails 3->4 not the README sry the readme is fine, after continuing to upgrade higher it vanished though ... either its still in some deprecated warning or i had an older version running at taht moment
