### ISSUE TITLE
best way to limit slug length?

### ISSUE THREAD

**Issue by ghost** [norman/friendly_id#190]
I managed to save an item that has an epically long slug, but now I can't perform CRUD on it via a browser due to ...

```
Request-URI Too Large

WEBrick::HTTPStatus::RequestURITooLarge
WEBrick/1.3.1 (Ruby/1.9.2/2011-07-09) at macbook.local:3000
```

What would be the best way to limit the slug's length. Why are they called slugs anyway, yuck.

**Comment by Dieglock** [comment]
+ another 1 to @Sjors. Was very handy...

**Comment by Empact** [comment]
@norman I think it was adopted by the newspaper industry based on its use in the typesetting industry: https://en.wikipedia.org/wiki/Slug_(typesetting)
