### ISSUE TITLE
Slug works with Chinese Character?

### ISSUE THREAD

**Issue by wakilo** [norman/friendly_id#304]
I followed the instruction of railscasts #314 and successfully add friendly_id. However it seems slug doesn't work with Chinese name.

here is the code

``` ruby
# /app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
end
```

Let's say I create an new article with Chinese name.

It seems FriendlyId is unable to save the Chinese name in slug column. So the URL still shows the id of the article.

If I do this without slug

``` ruby
# /app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name
end
```

It works but I have to ensure no duplicate name.

Any idea how to solve this?

**Comment by PascalPixel** [comment]
For other Google Searchers:

This is now achievable through the friendly_id.rb config file, all the way at the bottom you can enable transliteration, be sure to add the 'babosa' gem to your gemfile first.

**Comment by gwalshington** [comment]
@PascalPixel  Currently running into this issue too - how did you handle Chinese characters with Babosa? It's documentation does not list Chinese as a language it handles.

**Comment by PascalPixel** [comment]
@gwalshington I was working with Japanese at the time (here: http://www.kanjinerd.com/en/items/遏密) it should work out of the box, if you can't get it to work, I can give you source access, since I don't remember at this point!
