### ISSUE TITLE
apostrophes turn into a dash for slug value

### ISSUE THREAD

**Issue by aj0strow** [norman/friendly_id#329]
I'm sure a lot of thought went into making the slug string, but maybe reconsider turning apostrophes into dashes?

Ex:   Person's website   =>  person-s-website

Wouldn't it be better to have that turn into   =>  persons-website

I looked at the code and read through slug_generator.rb, but I wasn't really sure where to begin to try to make the change myself. Somewhere you just need:

slug_input.delete("'")

**Comment by toobulkeh** [comment]
this is related to https://github.com/norman/friendly_id/issues/419
