### ISSUE TITLE
Q: Is it possible not to use the slug, instead use the id in form_for?

### ISSUE THREAD

**Issue by artisr** [norman/friendly_id#375]

**Comment by sjaveed** [comment]
Just a +1 for this.  It's frustrating to have to generate urls manually when using form_for with friendly_id.

**Comment by parndt** [comment]
Unfortunately I'm not sure that I see a way to fix this.  FriendlyId uses `to_param` to generate its routes on the frontend (where you want friendly routing) so I am not sure how we'd be selective and/or know that you're using it inside a form?

**Comment by sjaveed** [comment]
A configuration option which allows the user to turn off the friendly behavior of routes application-wide would help.  I know we only use the friendly id in some specific situations and would gladly make a special call to the route methods for those scenarios.  This is the behavior right now:
```ruby
team = Team.last

team_path(team)  # returns /team/123-awesome-team-name - we need this only in special cases
team_path(team.id) # returns /team/123 - we need this all the time
polymorphic_path(team) # returns /team/123-awesome-team-name - used by form_for.  we don't need this
```
What we'd like:
```ruby
team_path(team) # should return /team/123
team_path(team.friendly_id) # should return /team/123-awesome-team-name
polymorphic_path(team) # should return /team/123
```
If that behavior can be flipped using a configuration directive, that would be awesome.

Thoughts?

**Comment by parndt** [comment]
@sjaveed I think that's the only way to have it.. disabled by default and opt-in.

How interested are you in implementing it?
@norman how interested are you in supporting this feature?

**Comment by sjaveed** [comment]
@parndt getting a pull request ready now

**Comment by sjaveed** [comment]
@parndt pull request #735 is ready for your critique :-)

**Comment by parndt** [comment]
:white_check_mark:
