### ISSUE TITLE
Way to override slug generation substitution of '-' for apostrophes?

### ISSUE THREAD

**Issue by brchristian** [norman/friendly_id#419]
I'm looking to override `friendly_id`'s substitution of a hyphen for an apostrophe.

It seems to me that the appropriate slug for "The Cat's Meow" should be `the-cats-meow` and not `the-cat-s-meow`.

Is there a way for me to control or override this behavior in `friendly_id`?

**Comment by toobulkeh** [comment]
I tried adding this to the config initializer, but it didn't work:

```ruby
  config.use Module.new {
    # Removes single quotes from dashes
    def normalize_friendly_id(string)
      super(string.gsub("'", ""))
    end
  }
```

Not sure why, but it works on the model just fine!
