### ISSUE TITLE
undefined method `friendly_id' for #<Class:0x1110ca2d0>

### ISSUE THREAD

**Issue by dgwmfo** [norman/friendly_id#425]
Hi:

I just installed friendly_id 4.0.9 in my rails 3.1 app. Here are the top lines of my Gemfile:

source "http://rubygems.org"

gem "rails", "3.1.12"
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql2', "0.3.13"
gem 'rake', "0.8.7"
gem 'bundler', "1.0.22"
gem 'will_paginate', "3.0.0"
gem 'awesome_nested_set', "1.4.3"
gem 'mini_magick', "3.2"
gem "friendly_id", "4.0.9"

I'm running under Ruby 1.8.7.

When I try to view my app locally (OSX 10.6.8) by pointing the browser to http://localhost:3000, I get the following error trace:

NoMethodError in DefaultController#index

undefined method `friendly_id' for #Class:0x1110ca2d0
Rails.root: /Users/dean/genlighten

Application Trace | Framework Trace | Full Trace
activerecord (3.1.12) lib/active_record/base.rb:1099:in `method_missing'
app/models/user.rb:66
activesupport (3.1.12) lib/active_support/dependencies.rb:456:in`load'
activesupport (3.1.12) lib/active_support/dependencies.rb:456:in `load_file'
activesupport (3.1.12) lib/active_support/dependencies.rb:640:in`new_constants_in'
activesupport (3.1.12) lib/active_support/dependencies.rb:455:in `load_file'
activesupport (3.1.12) lib/active_support/dependencies.rb:342:in`require_or_load'
activesupport (3.1.12) lib/active_support/dependencies.rb:489:in `load_missing_constant'
activesupport (3.1.12) lib/active_support/dependencies.rb:181:in`const_missing'
activesupport (3.1.12) lib/active_support/dependencies.rb:179:in `each'
activesupport (3.1.12) lib/active_support/dependencies.rb:179:in`const_missing'
activesupport (3.1.12) lib/active_support/dependencies.rb:501:in `load_missing_constant'
activesupport (3.1.12) lib/active_support/dependencies.rb:181:in`const_missing'
activesupport (3.1.12) lib/active_support/dependencies.rb:179:in `each'
activesupport (3.1.12) lib/active_support/dependencies.rb:179:in`const_missing'
lib/authenticated_system.rb:236:in `login_from_cookie'
activesupport (3.1.12) lib/active_support/callbacks.rb:430:in`_run__202025261__process_action__656296333__callbacks'
activesupport (3.1.12) lib/active_support/callbacks.rb:386:in `send'
activesupport (3.1.12) lib/active_support/callbacks.rb:386:in`_run_process_action_callbacks'
activesupport (3.1.12) lib/active_support/callbacks.rb:81:in `send'
activesupport (3.1.12) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.1.12) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.1.12) lib/action_controller/metal/rescue.rb:17:in`process_action'
actionpack (3.1.12) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
activesupport (3.1.12) lib/active_support/notifications.rb:53:in`instrument'
activesupport (3.1.12) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.1.12) lib/active_support/notifications.rb:53:in`instrument'
actionpack (3.1.12) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.1.12) lib/action_controller/metal/params_wrapper.rb:201:in`process_action'
activerecord (3.1.12) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.1.12) lib/abstract_controller/base.rb:121:in`process'
actionpack (3.1.12) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.1.12) lib/action_controller/metal.rb:193:in`dispatch'
actionpack (3.1.12) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.1.12) lib/action_controller/metal.rb:236:in`action'
actionpack (3.1.12) lib/action_dispatch/routing/route_set.rb:71:in `call'
actionpack (3.1.12) lib/action_dispatch/routing/route_set.rb:71:in`dispatch'
actionpack (3.1.12) lib/action_dispatch/routing/route_set.rb:35:in `call'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in`call'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `recognize'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:68:in`optimized_each'
rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in`call'
actionpack (3.1.12) lib/action_dispatch/routing/route_set.rb:538:in `call'
actionpack (3.1.12) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
rack (1.3.10) lib/rack/etag.rb:23:in `call'
rack (1.3.10) lib/rack/conditionalget.rb:25:in`call'
actionpack (3.1.12) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.1.12) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.1.12) lib/action_dispatch/middleware/flash.rb:243:in `call'
rack (1.3.10) lib/rack/session/abstract/id.rb:195:in`context'
rack (1.3.10) lib/rack/session/abstract/id.rb:190:in `call'
uploader (3.1.4) lib/uploader/middleware/flash_session_cookie_middleware.rb:15:in`call'
actionpack (3.1.12) lib/action_dispatch/middleware/cookies.rb:331:in `call'
activerecord (3.1.12) lib/active_record/query_cache.rb:64:in`call'
activerecord (3.1.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in `call'
actionpack (3.1.12) lib/action_dispatch/middleware/callbacks.rb:29:in`call'
activesupport (3.1.12) lib/active_support/callbacks.rb:392:in `_run_call_callbacks'
activesupport (3.1.12) lib/active_support/callbacks.rb:81:in`send'
activesupport (3.1.12) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.12) lib/action_dispatch/middleware/callbacks.rb:28:in`call'
actionpack (3.1.12) lib/action_dispatch/middleware/reloader.rb:68:in `call'
rack (1.3.10) lib/rack/sendfile.rb:101:in`call'
actionpack (3.1.12) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.1.12) lib/action_dispatch/middleware/show_exceptions.rb:47:in`call'
railties (3.1.12) lib/rails/rack/logger.rb:13:in `call'
rack (1.3.10) lib/rack/methodoverride.rb:24:in`call'
rack (1.3.10) lib/rack/runtime.rb:17:in `call'
activesupport (3.1.12) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
rack (1.3.10) lib/rack/lock.rb:15:in `call'
actionpack (3.1.12) lib/action_dispatch/middleware/static.rb:61:in`call'
railties (3.1.12) lib/rails/engine.rb:456:in `call'
railties (3.1.12) lib/rails/application.rb:143:in`call'
rack (1.3.10) lib/rack/content_length.rb:14:in `call'
railties (3.1.12) lib/rails/rack/log_tailer.rb:14:in`call'
rack (1.3.10) lib/rack/handler/webrick.rb:59:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:92:in`each'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:23:in`start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
rack (1.3.10) lib/rack/handler/webrick.rb:13:in`run'
rack (1.3.10) lib/rack/server.rb:268:in `start'
railties (3.1.12) lib/rails/commands/server.rb:70:in`start'
railties (3.1.12) lib/rails/commands.rb:54
railties (3.1.12) lib/rails/commands.rb:49:in `tap'
railties (3.1.12) lib/rails/commands.rb:49
script/rails:6:in`require'
script/rails:6

In my User model, lines 65 and 66 reference FriendlyID:

  extend FriendlyId
  friendly_id :login, :use => :slugged

lib/authenticated_system.rb:236:in `login_from_cookie' refers to the following code. Line 236 begins with user = cookies...

  # Called from #current_user.  Finally, attempt to login by an expiring token in the cookie.
  def login_from_cookie
    user = cookies[:auth_token] && User.find_by_remember_token(cookies[:auth_token])
    if user && user.remember_token?
      user.remember_me
      cookies[:auth_token] = { :value => user.remember_token, :expires => user.remember_token_expires_at }
      self.current_user = user
    end
  end

I noted in an earlier issue someone had a similar problem, but with an older version of FriendlyID. Do I need to upgrade from 4.0.9 to fix this?

Thanks very much,

Dean Richardson
Genlighten.com

**Comment by AvaelKross** [comment]
another way to get this error - forget to "extend FriendlyId" :)

**Comment by alex223125** [comment]
I would also check if `extend FriendlyId` is added to model (just in case if someone having same error)

Example:
```
class Articles < ApplicationRecord

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders, :history]


  private

  def slug_candidates
    [ :title,
      [:title, :id]
    ]
  end

end

```
