### ISSUE TITLE
Rails 4, Active Admin and friendly ID ActiveRecord::RecordNotFound

### ISSUE THREAD

**Issue by grimmwerks** [norman/friendly_id#441]
I saw that there was something similar but it was for rails 3; I'm trying to get this to work with active admin in rails 4 and unsure what I'm doing wrong.

If I configure config.use :finders in the friendly_id initializer it works; but I wanted to keep the default.

I've got an Episode class that is using friendly_id.  I've set the ActiveAdmin.register.Episode so that show is like this:

``` ruby
show do
  @episode = Episode.friendly.find(params[:id])
end
```

But it's still throwing the error? Something I'm doing?

**Comment by wqsaali** [comment]
+1 to @AlbertoValenzuela

**Comment by knightstick** [comment]
For those of you using FriendlyID 5.1+, this will work as you expect, with a fallback for plain ID's instead of a friendly slug:
```
ActiveAdmin.register Category do
  controller do
    def find_resource
      scoped_collection.friendly.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      scoped_collection.find(params[:id])
    end
  end
end
```

**Comment by joshkinabrew** [comment]
Ran in to this today, and I ended up using this code:

```ruby
ActiveAdmin.register Category do
  controller do
    def find_resource
      scoped_collection.friendly.find(params[:id])
    end
  end
end
```

No need for the extra rescue clause. According to the friendly_id docs, as of 5.0+
`Model.friendly.find(1)` and `Model.friendly.find('slugged-slug')` work the exact same way. 

ref: http://norman.github.io/friendly_id/file.Guide.html#Performing_Finds_with_FriendlyId

**Comment by rolandoalvarado** [comment]
> ```ruby
> class User < ActiveRecord::Base
> 
>   extend FriendlyId
>   friendly_id :username, :use => [:finders]
> ```

This one solves my problem.
