### ISSUE TITLE
Friendly_id 5 rc1 - single table inheritance issue

### ISSUE THREAD

**Issue by alpracka** [norman/friendly_id#447]
Hello,

I've just tried Rails 4 with the latest friendly_id 5 rc1. My example:

```
class User < ActiveRecord::Base
  extend FriendlyId
end

class Client < User
  friendly_id :name, use: :slugged
  validates_presence_of :name 
end
```

When I try to create and save new user in console like:

```
user = User.new
user.name = "Bob Dylan"
user.password = "password"
user.save
```

I get this error:

```
NoMethodError: undefined method `' for #<User:0x00000007843b20>
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in `method_missing'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb:131:in `method_missing'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/friendly_id-5.0.0.rc1/lib/friendly_id/base.rb:234:in `friendly_id'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/activemodel-4.0.0/lib/active_model/validator.rb:151:in `block in validate'
... and continues ...
```

Creating Client is OK. Interesting is when I create Client like a first and then User, there is no error. 

This is might bad approcach. What I want is more inherited models from User with different friendly_id parameter. And the User model should not use slugged id.

Best regards, thanks for help.

**Comment by neohunter** [comment]
I've a similar problem:

```ruby
class User < ApplicationRecord
  # ... nothing about friendly id
```

and:

```ruby
class Translator < User
  extend FriendlyId
  friendly_id :first_name, use: :slugged
```

It raise: 

```NoMethodError: undefined method `friendly' for #<User::ActiveRecord_Relation:0x007fdac68b0030>
Did you mean?  friendly_id?```

if I add `  extend FriendlyId` to `User` it works, but, why? if extend is already on `Translator` class.
