### ISSUE TITLE
How can I disable friendly-id to for setting the slug to all lowercase?

### ISSUE THREAD

**Issue by wlgithub** [norman/friendly_id#456]
Dear Norman,

In my application I'd like to to create slug from the id of the model directly using a encode function, which generates a string, for example:  id value of 10 will be generating string "sxUoMs", then I want to use this as the slug.name value and then I will direct user to http://mysite.com/sxUoMs  instead of /mysite.com/sxuoms/ 

How can I do that ? 

There is obvious reason for using this approach, because the usual way of using name for slug requires the model name field to be unique, which is not ideal. For example books can have the same name.  id is always unique and encode(id) will always generate a unique string and adds a layer of obfuscation

W

**Comment by mockdeep** [comment]
@norman looks like there's a question to this effect on SO that hasn't been answered. Could you help?

http://stackoverflow.com/questions/34707159/how-to-make-case-sensitive-urls-with-rails-friendly-id

**Comment by mockdeep** [comment]
Nm, did some source diving and found it:

```ruby
def normalize_friendly_id(value)
  value.to_s.parameterize(preserve_case: true)
end
```
