### ISSUE TITLE
Supporting sequence numbers for conflicting slugs in friendly_id 5 

### ISSUE THREAD

**Issue by gaganawhad** [norman/friendly_id#480]
Thanks for all the work on friendly_id 5

While slug candidates and UUID both make for good solutions to resolve conflicts in a slug, I would like to use sequence numbers in slugs ('--2', '--3' etc.) in cases of conflict (which is the default solution used in friendly_id 4). 

I do not have any other reliable slug candidate than the one I am using and UUIDs are a bit too 'unfriendly' for my application. 

I would really appreciate any pointers on how I can go about doing that. If I can contribute to documentation / code for this, I will. 

p.s. While this issue may not qualify for a bug, I thought of creating an issue instead of an SO question because I think this is more tightly integrated with the software.

**Comment by dortonway** [comment]
Why can't we just use id instead of sequence or UUID to have prettier urls?

**Comment by norman** [comment]
> Why can't we just use id instead of sequence or UUID to have prettier urls?

You can certainly do that if you want to, but not everybody does. If you want to use the id in the URL you don't need FriendlyId - a method like this in your model is sufficient:

```ruby
def to_param
  "#{id}-#{some_method.parameterize}"
end
```
