### ISSUE TITLE
Slug is not generated when saving model in Rails Admin

### ISSUE THREAD

**Issue by umate** [norman/friendly_id#488]
Hi,

I've been using rails_admin (0.5.0), friendly_id (4.x) and rails (3.2.14) and had the next code:

``` ruby
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :generated_slug, use: :slugged

  def generated_slug
    title
  end
end
```

Slug has been generating perfectly.
Then I switched to rails 4.0.0 and friendly_id 5.0.1, rails_admin is still 0.5.0.
As a result method generated_slug is not called when saving model in Rails Admin and the slug in not generating automatically.
But everything is still ok when saving model in Rails console.

Do you have any thoughts on that?

**Comment by hajder** [comment]
I know this is an old issue but I'd like to share my concerns.
I don't think overwriting setter method is a right way to handle this. FriendlyId should either generate a slug on `blank?` value as well or expose this as a configuration option.

**Comment by hampelm** [comment]
Bumping this as well -- is there a a more generic way to enable automatically generating slugs in Rails Admin?

**Comment by stockandawe** [comment]
I have the same issue with Rails 4.2.4 and friendly_id 5.1.0. 

@umate's solution of overwriting the setter works. +1 for having a better way to do this.

**Comment by invulsion** [comment]
Does anybody have found a solution? I'm having the same issues and overriding the setter method in every model doesn't feel a good idea.

**Comment by kannans** [comment]
It required `slug` field. If the table doesn't have `slug` field it might throw error  as `undefined`.
Create new migration to table(pages) with `slug` field. 

Save existing records with new slug values ` Page.find_each(&:save)`

Read the [guide](http://norman.github.io/friendly_id/file.Guide.html) for more details.
