### ISSUE TITLE
uninitialized constant Product::FriendlyId

### ISSUE THREAD

**Issue by MikeAndrianov** [norman/friendly_id#522]
Hi there! Could you please help me with this issue:

uninitialized constant Product::FriendlyId
    from /home/mike/workspace/test_store/app/models/product.rb:5:in `<class:Product>'
    from /home/mike/workspace/test_store/app/models/product.rb:1:in`<top (required)>'
    from /home/mike/workspace/test_store/app/admin/product.rb:1:in `<top (required)>'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-bae6cec4c38a/lib/active_admin/application.rb:179:in`load'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-bae6cec4c38a/lib/active_admin/application.rb:171:in `block in load!'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-bae6cec4c38a/lib/active_admin/application.rb:171:in`each'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-bae6cec4c38a/lib/active_admin/application.rb:171:in `load!'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-bae6cec4c38a/lib/active_admin/application.rb:195:in`routes'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-bae6cec4c38a/lib/active_admin.rb:80:in `routes'
    from /home/mike/workspace/test_store/config/routes.rb:5:in`block in <top (required)>'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:316:in `instance_exec'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:316:in`eval_block'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:294:in `draw'
    from /home/mike/workspace/test_store/config/routes.rb:1:in`<top (required)>'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application/routes_reloader.rb:40:in`each'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application/routes_reloader.rb:16:in`reload!'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application.rb:102:in `reload_routes!'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-bae6cec4c38a/lib/active_admin/application.rb:245:in`block in attach_reloader'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:397:in `_run__930234509__prepare__callbacks'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in`run_callbacks'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.0/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.0/lib/action_dispatch/middleware/reloader.rb:46:in`prepare!'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/console/app.rb:28:in `reload!'
    from (irb):106
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in`start'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /home/mike/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:64:in`<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in`<main>'2.0.0p247 :107 > 

I'm using friendly_id 5.0.2 version

**Comment by nuheluxulu** [comment]
Same issue, had to restart the server
