### ISSUE TITLE
friendly scope does not work if load_and_authorize_resource before_action of  CanCan exists

### ISSUE THREAD

**Issue by scaryguy** [norman/friendly_id#544]
Hi,

I'm using Rails 4, Devise, CanCanCan and friendly_id.

I have a controller called `episodes_controller.rb` and it's protected by Devise and CanCan. I'm just trying to browse Edit page of an episode which has `friendly_id` slug set up, and I get this error:

```
Couldn't find Episode with id=episode-slug
```

In the meantime, my `edit` method looks like this:

``` ruby
def edit
    @episode = Episode.friendly.find(params[:id])
  end
```

I've realized that this behavior doesn't happen as I remove the `load_and_authorize_resource` before action which comes with CanCan. When I comment out `load_and_authorize_resource`, the episode with the slug is found and edit page appears as it supposed to be.

Another interesting thing:
When I add `:finders` to my `use` array in my `Episode` model, and change `Episode.friendly.find(params[:id])` with `Episode.find(params[:id])` everything works as expected.

So it's clear that there is something wrong with `friendly` scope of `friendly_id` gem and CanCan's `load_and_authorize_resource` method.

Is this a bug or am I doing something wrong?

Thank you

**Comment by pamit** [comment]
Thank you @mrusa

**Comment by ahmad19** [comment]
Thank you @mrusa

**Comment by sergiovilar** [comment]
Thanks @mrusa, it works like a charm.

**Comment by 1v** [comment]
> load_and_authorize_resource :find_by => :slug

For Rspec controller tests it will require as is:
```
get :edit, { id: article.slug }
```

**Comment by xymbol** [comment]
@1v Have you tried `article.to_param`?

**Comment by 1v** [comment]
@xymbol You right, passing just instance is ok.

**Comment by piedoom** [comment]
@mrusa that works for the slug, but seems to break using IDs instead.  Any idea on how to fix that?
