### ISSUE TITLE
Override `find_by_id`?

### ISSUE THREAD

**Issue by mockdeep** [norman/friendly_id#605]
One thing that would be nice is to be able to query for an object and decide what to do if it turns up:

``` ruby
user = User.find_by_id(params[:id])
unless user
  # render an error
end
```

But with friendly_id, I have to rescue an error to pull this off:

``` ruby
begin
  user = User.friendly.find(params[:id])
rescue ActiveRecord::RecordNotFound
  # render error
end
```

It would be nice if I could do `User.friendly.find_by_id(params[:id])` instead.

**Comment by tansaku** [comment]
I agree with @mockdeep - friendly seems to be using find differently from AR

in AR `find` will just return nil if the model is missing, and `find!` will raise an error - it would prevent confusion if friendly_id followed the same convention

**Comment by xymbol** [comment]
>in AR find will just return nil if the model is missing, and find! will raise an error - it would prevent confusion if friendly_id followed the same convention

@tansaku That is misleading and incorrect.

You're referring to `ActiveRecord::FinderMethods#find` and, even though its name might not suggest so, it **does raise** if one or more records cannot be found.

http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find

Adding a comment to avoid confusion.

**Comment by saiqulhaq** [comment]
instead rescuing `ActiveRecord::RecordNotFound`

``` ruby
module FriendlyId
  module FinderMethods
    def find_by_id(*args)
      find(*args)
    rescue ActiveRecord::RecordNotFound
    end
  end
end
```

I think it would be faster to use following method

```ruby
module FriendlyId
  module FinderMethods
    def find_by_id(id)
      first_by_friendly_id(id)
    end
  end
end
```

Reference: https://github.com/norman/friendly_id/blob/master/lib/friendly_id/finder_methods.rb

**Comment by swards** [comment]
I ran into this to.  Decided to bypass `.friendly` with:
```
    user = User.find_by_slug(params[:id]) || User.find_by_id(params[:id])
```
