### ISSUE TITLE
Using the history module breaks slug_candidates

### ISSUE THREAD

**Issue by oboxodo** [norman/friendly_id#632]
I have a perfectly working model with:
```ruby
class Case < ActiveRecord::Base
  self.primary_key = :case_id
  friendly_id :slug_candidates, use: :slugged

  private

  def slug_candidates
    [
      :name,
      [:name, :full_citation]
    ]
  end
end
```

That has been working perfectly. I'm including the `primary_key` call just in case it's important.

Today I tried to add the `history` module like this:
```ruby
  friendly_id :slug_candidates, use: [:slugged, :history]
```

After that (and running the migration, etc) when I try to add a Case which has the same `name` as another existing one, I get a Postgres error saying the slug is not unique. It's not trying the second option in the `slug_candidates` array. Removing the `history` module makes it work again.

**Comment by norman** [comment]
@oboxodo Happy New Year! What version of FriendlyId? Candidate handling changed slightly in 5.1.0.beta.1, so if it's not that version then please try it and report back.

**Comment by oboxodo** [comment]
Happy New Year, Compay!

So it turns out that (as usual) I was wrong. FTR the versions I'm using are rails 4.1.6 and friendly_id 5.0.4.

My mistake was trying to regenerate the slug for a Case, without having populated the `friendly_id_slugs` table for every existing record before.

So now, with an empty `friendly_id_slugs` table I ran this in the console:
```ruby
Case.unscoped.find_each {|c| c.send(:create_slug)}
```

That populated the history table with the current slugs. After that, regenerating a slug worked fine and took my 2nd ption from the `slug_candidates`. Before it wasn't able to find the existing conflicting slug because it didn't exist in the history table yet (although it existed in the cases table).

Here's for a great 2015. Cheers!

PS: I decided to keep my dependency with 5.0.4 because it's the latest stable. Should I really upgrade to 5.1.0.beta1 even being a beta? Is 5.0.4 **that** buggy?

**Comment by norman** [comment]
> Is 5.0.4 that buggy?

No. We're bumping the minor version number because there are some small differences in behavior that some applications could in theory be depending on; check the Changelog for specifics to see if it affects you.

> Should I really upgrade to 5.1.0.beta1 even being a beta? 

It's up to you. At the moment the finders module in 5.0 doesn't work on Active Record 4.2, but does in 5.1, but I'm going to backport support to a 5.0.5 release when I release the final version of 5.1.0 (probably this weekend).
