### ISSUE TITLE
5.1 release date

### ISSUE THREAD

**Issue by arunagw** [norman/friendly_id#633]
Hey @norman thanks for great gem. I was wondering when you will be able to release 5.1 final version as it's in beta right now.

It's not an issue so can close this. Didn't find any other place for asking about this.

thanks

**Comment by norman** [comment]
Hi @arunagw I'm planning to do it after work today, as well as a new version of the 5.0 series which backports the Rails 4.2 support. If something comes up and I don't get to it today, then this weekend for sure.

**Comment by arunagw** [comment]
Thanks.
