### ISSUE TITLE
Friendly ID for duplicates

### ISSUE THREAD

**Issue by artem-galas** [norman/friendly_id#634]
Let's say we have 2 posts with the same titles: "superheros". The first post should have url superheros-alternative-1 and the second one should have superheros-alternative-2. The problem is that when I am updating a title of one of these posts, the url should change for both of them. I mean if I change a title to "marvel", then the urls should become the following marvel-alternative-1 and marvel-alternative-2. Now I have the next code

```ruby
class Post < ActiveRecord::Base

  before_update :update_slug

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  def update_slug
    title = Post.find(self.id).title
    Post.where(title:title).each do |post|
      post.update_column(:title,self.title)
    end
  end
end

**Comment by parndt** [comment]
So do you mean that if you change the title for one of your posts, that it should change the title of all of the other posts with the same title too?

**Comment by artem-galas** [comment]
The given code already does this, I need that copies have their URL updated. 
I also forgot to mention that the following code allows fixing conflicts so instead of hash (which is used by default for identical URLs) there is "alternative":

```ruby
def resolve_friendly_id_conflict(candidates)
convertText=self.title   
slug=convertText+"-alternative"
    sequence = Post.where("slug like '#{slug}-%'").count + 1
    "#{slug}-#{sequence}"
  end

**Comment by parndt** [comment]
The probable reason that the URLs are not being updated is that you're using `update_column` which bypasses all callbacks and just issues an UPDATE SQL command.  You may find better success with code like this:

```ruby
class Post < ActiveRecord::Base

  before_update :update_slug, :if => :title_changed?

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  def update_slug
    title = Post.find(self.id).title
    Post.where(title: title).each do |post|
      post.update_attribute(:title, self.title)
    end
  end
end
```

Untested, but I think it might help you.

**Comment by artem-galas** [comment]
Thanks for your prompt reply. Your solution causes an infinite cycle because `update_attribute` also calls `before_update` callback.
A better solution would  be using the method described in `update_slug` inside a controller and not in a model. (http://stackoverflow.com/questions/27918168/friendly-id-for-duplicates)
Thanks anyway :)

**Comment by artem-galas** [comment]
Hi everyone, i have a question about `resolve_friendly_id_conflict(candidates)`: is this callback called if field was changed? Because if i create  a new post with the same title and call update function, then `resolve_friendly_id_conflict(candidates)` doesn't work. But if I change title in this update, the function is called.

**Comment by norman** [comment]
No, you need to set the slug to nil in order for a new slug to be generated. This is described in the docs for the sluggable module, take a look at the Guide.
