### ISSUE TITLE
Using @ with friendly_id 

### ISSUE THREAD

**Issue by aditya01933** [norman/friendly_id#640]
I want to use '@' before the link in friendly_id I have username and I am saving username in database with '@' symbol. Its working correctly. But Friendly_id is showing

example.com/username
and I want

example.com/@username
How can I do that ?

**Comment by norman** [comment]
Check the docs for overriding the normalize_friendly_id method.

http://www.rubydoc.info/github/norman/friendly_id/master/FriendlyId/Slugged#normalize_friendly_id-instance_method

Something like "@#{super}" should work.

**Comment by aditya01933** [comment]
I found it
