### ISSUE TITLE
Bypassing validations and strange behaviour

### ISSUE THREAD

**Issue by alpracka** [norman/friendly_id#642]
Hi Norman and others!

I'm facing a problem (bug maybe) when trying to save object which was created already with validation bypass `@project.save(validate: false)`. I've created demonstration app with test which fails but should pass in my opinion - https://github.com/alpracka/testfriendly. Here is also short screenrecord: http://n1dev.com/system/data/testfriendly.mov (3MB)

```
Test file: spec/features/projects_spec.rb
Run: bundle exec rspec

Versions:
friendly_id 5.1.0
rails 4.2.0
ruby 2.1.3p242
```

**Comment by norman** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by norman** [comment]
Thanks for such an outstanding bug report, and my apologies for taking so long to respond. I agree this should be fixed, and am looking into the best solution. In the mean time, this workaround would help in your application:

```ruby
class Project < ActiveRecord::Base

  # Friendly Id
  extend FriendlyId
  friendly_id :name, :use => :slugged

  # Validations
  validates_presence_of :name, :description
  after_validation :unset_slug_if_invalid

  def unset_slug_if_invalid
    if errors.present? && slug_changed?
      self.slug = slug_was
    end
    true
  end
end
```

**Comment by norman** [comment]
This issue is now resolved in master and will go out in gem version 5.2.0.beta.1 some time this week.

**Comment by norman** [comment]
This is now out in [5.2.0.beta.1](https://rubygems.org/gems/friendly_id/versions/5.2.0.beta.1). No timetable for stable release yet, but probably within a couple weeks.

**Comment by alpracka** [comment]
Awesome! Thank you.

**Comment by rachel-carvalho** [comment]
I've just stumbled onto this problem myself, is there an ETA for this fix to be released? Thank you!

**Comment by norman** [comment]
@rachel-carvalho Sorry I've been a bit slow to put out the new release, there were a few additional things I wanted to work on and never quite got to. I hope to put out a new release in a few weeks but I can't give your a hard date. In the mean time I'd suggest you try 5.2.0.beta.1, it's more stable than the release number might imply.

**Comment by rachel-carvalho** [comment]
I appreciate the fast reply! I'll give the beta version a try, is there any kind of change log, so I can know what to expect to act differently in this version?

**Comment by norman** [comment]
Yes: https://github.com/norman/friendly_id/blob/master/Changelog.md
