### ISSUE TITLE
Regenerate slugs with scope

### ISSUE THREAD

**Issue by Linuus** [norman/friendly_id#647]
Hi!

I have a model `Page` which belongs to a `Department`.

```ruby
class Page < ActiveRecord::Base
  include FriendlyId
  belongs_to :department

  friendly_id :title, use: [:slugged, :history]
  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end
```

Now I changed this so the slug is scoped on the department.

```ruby
class Page < ActiveRecord::Base
  include FriendlyId
  belongs_to :department

  friendly_id :title, use: [:slugged, :history, :scoped], scope: :department

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end
```

However, now I want to update all slugs so they contain the scope.

How can I do that? I tried returning `true` in `should_generate_new_friendly_id?` but that didn't do anything.

The only thing I have found that works is to change the title, save, change the title back, and save.

Is there an easier way to just update the slugs?

**Comment by norman** [comment]
Setting the slug to nil and then saving the record will cause it to be regenerated. Something like:

```ruby
Page.transaction do
  Page.find_each do |page|
    page.slug = nil
    page.save!
  end
end
```

should do the trick.

**Comment by Linuus** [comment]
@norman I tried that but it does not do anything. It doesn't update the `scope` column and it does not create a new entry in the `friendly_id_slugs` table.

I use version 5.0.4 btw.

**Comment by norman** [comment]
Sorry about that - if you want to preserve history you can try updating the scope on the slug record:

```ruby
Page.transaction do
  Page.find_each do |page|
    page.slug = nil
    page.save!
    page.slugs.update_all :scope => page.serialized_scope
  end
end
```

but depending on the state of your application (i.e., in production for years with FriendlyId and thousands of historic slug records) this could possibly lead to inconsistencies. Your safest option would be to blow away all the historic slugs and start from scratch at a consitent state:

```ruby
Page.transaction do
  Page.find_each do |page|
    page.slugs.destroy_all
    page.slug = nil
    page.save!
  end
end
```

**Comment by norman** [comment]
I haven't heard back in a while so I assume your question has been answered. Closing the issue.

**Comment by Linuus** [comment]
Sorry that I'm a bit slow. I haven't finished this yet so I'm not sure what approach I'll take. Anyway, this can be closed.

**Comment by Linuus** [comment]
Hello again!

I have a question about this old issue.

- What kind of inconsistencies could occur if I don't delete all the old slugs?
