### ISSUE TITLE
How do I disable Model.friendly.find finding by id on v5.x?

### ISSUE THREAD

**Issue by terenceponce** [norman/friendly_id#648]
With the addition of `Model.friendly.find` on 5.x, is there a way to disable finding a record by its actual ID and only allow finding by slug?

```ruby
Post.friendly.find(1) # I want this to raise an ActiveRecord::RecordNotFound error
```

 I understand I can just use `find_by_slug`, but I feel like I wouldn't need to use this gem at all if I can just manually find a record by its slug.

**Comment by parndt** [comment]
Can you help us to understand the reasoning behind this?

**Comment by norman** [comment]
No, there's no extra API for this since find_by_slug is sufficient. An alternate strategy is to find the record and then raise an error if the model.id.to_s == params[:id]. By all means avoid adding in FriendlyId if your app doesn't need it - it adds overhead and if you don't need it leaving it out is a win.

**Comment by terenceponce** [comment]
@parndt I wanted to restrict users from accessing a resource if they entered the ID of the record.

```
/posts/slug-of-1 # returns 200
/posts/1 # returns 404
```

Unfortunately, this won't work because `Post.friendly.find(1)` will work and return the record.

@norman Okay, cool. Thanks for clarifying!

**Comment by parndt** [comment]
In your controller, you could do something along these lines:

```ruby
before_action :reject_unfriendly_id

private
def reject_unfriendly_id
  if params[:id].to_i == params[:id]
    # reject
  end
end
```

**Comment by terenceponce** [comment]
@parndt That's a great idea. Thanks!

**Comment by eliotsykes** [comment]
The gem provides `find_by_friendly_id` which can be called on `friendly` or on a scope. For example all of these will raise `ActiveRecord::RecordNotFound` if a numeric id is used as the argument:

```rb
# Works:
Post.friendly.find_by_friendly_id(1)
Post.all.find_by_friendly_id(1)
Post.published.find_by_friendly_id(1)


# Does not work, must be chained:
Post.find_by_friendly_id(1)
```
