### ISSUE TITLE
Can't configure sequence_separator

### ISSUE THREAD

**Issue by chaostheory** [norman/friendly_id#650]
Currently if you try to configure the sequence separator in the FriendlyId initializer, you'll get an undefined method error. Looking at the Configuration class, it isn't defined.

If you try to configure it via the 'friendly_id' setting in the model, nothing happens. 

http://stackoverflow.com/questions/25480715/how-do-you-define-sequence-separator-for-friendlyid-5-0-4-on-rails-4-1-4

**Comment by aidzas** [comment]
Me too

**Comment by norman** [comment]
Thanks for reporting. The sequence separator is a part of the `:slugged` addon, which is why you're not seeing it defined in the Configuration class. Try adding `config.use :slugged` in the initializer before your line of code that configured the sequence_separator value.

This should be mentioned in the comments in the initializer; it's a bug that it isn't, and we'll fix it.

**Comment by chaostheory** [comment]
cool - no problemo and much appreciated for your great work

**Comment by nathan-eko** [comment]
So this explains why the initializer wasn't working, but why can't we set the separator on the models themselves? 

I'm doing the same basic thing as is mentioned in that SO question and it's having absolutely no effect for me:

```extend FriendlyId
  friendly_id :identifier, use: :slugged, sequence_separator: '.'```

Separator remains the default `-`

**Comment by valentine** [comment]
Maybe it was just me, but I had the misconception for a few hours that the sequence separator was used to separate the content of the slug itself (e.g. switching from `this-is-a-slug` to `this_is_a_slug`).

This isn't the case — it's just to separate the slug from the generated UUID. You need to write your own slug processing method to change the actual slug separator.

I only realised that after reading through [slugged.rb](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/slugged.rb).

Anyway, just posting it here for the benefit of anyone else searching for this issue.
