### ISSUE TITLE
Correct way to integrate

### ISSUE THREAD

**Issue by imshenitsky** [norman/friendly_id#653]
I want to leave my urls for the admin area (I don't use active_admin or similar) in an old way:
```
/admin/products/5
/admin/categories/3
```
I know I can achieve this by passing an ID:
`admin_product_images_path(@product.id)` and it gives me link with no friendly_id.
But there are many places when i should do this: products, comments, images, carts, categories..so on.
Besides I dont know how to change this:
```ruby
<%= form_for [:admin, @product] do |f| %>
```
generates `<form action="/admin/products/watt-price">`

Actually all work because `Product.friendly.find` will work with both: record id and friendly_id.
But it turns me into a hard way of integration because friendly_id should by applied for the user area only.

**Comment by imshenitsky** [comment]
I want to leave my urls for the admin area (I don't use active_admin or similar) in an old way:
```
/admin/products/5
/admin/categories/3
```
I know I can achieve this by passing an ID:
`admin_product_images_path(@product.id)` and it gives me link with no friendly_id.
But there are many places when i should do this: products, comments, images, carts, categories..so on.
Besides I dont know how to change this:
```ruby
<%= form_for [:admin, @product] do |f| %>
```
generates `<form action="/admin/products/watt-price">`

Actually all work because `Product.friendly.find` will work with both: record id and friendly_id.
But it turns me into a hard way of integration.

**Comment by norman** [comment]
You can override to_param method in all the models you want to do this for, as described in #641.

In the places you want the friendly id in the URL, do

```ruby
foo_path(@foo.friendly_id) 
```

to generate urls.

**Comment by imshenitsky** [comment]
it works only in such case:
```ruby
  def to_param
    id.to_s
  end
```
It produces an error otherwise: `undefined method empty? for 10:Fixnum`
http://prntscr.com/6en63o

**Comment by norman** [comment]
Yes - that looks correct - sorry, I was typing this from memory not trying it in an application as I wrote.
