### ISSUE TITLE
Can we provider a functionality to generate slug in sequence in case of duplication?

### ISSUE THREAD

**Issue by anujaware** [norman/friendly_id#654]
In Latest version we have provided Candidates to avoid using ugly UUIDs. But can we provide option to get these slugs in sequence in case of duplication same as in previous version?

**Comment by norman** [comment]
Yes, that feature will be added in the next version, though there's currently no timetable for the release. See [this pull request](https://github.com/norman/friendly_id/pull/644) for more details.

**Comment by anujaware** [comment]
Thank you for the reply. 
Is that pull request is valid? Because test cases are failing. I will try if we don't have any implementation ready for this feature.

**Comment by norman** [comment]
Some work is still needed for edge cases, but it appears fairly solid to
me. I do not recommend you use it in a production application but if you
have an in-development application and want to use it now, then feel free.
If you discover any issues along the way please let us know!
