### ISSUE TITLE
History with scopes and non-unique slugs

### ISSUE THREAD

**Issue by burmashave** [norman/friendly_id#656]
The documentation recommends querying through the relation when using scopes where the slug isn't unique:

> If you are using scopes your friendly ids may not be unique, so a simple find like:

>     Restaurant.friendly.find("joes-diner")
> may return the wrong record. In these cases it's best to query through the relation:

>     @city.restaurants.friendly.find("joes-diner")
> Alternatively, you could pass the scope value as a query parameter:

>     Restaurant.where(:city_id => @city.id).friendly.find("joes-diner")

In my experience the **:history** addon only worked when passing the scope as a query parameter. I couldn't get friendly_id to find the record using previous slugs when querying through the relation.

Not sure if anyone else has had this experience, but wanted to leave a note for the documentation.

**Comment by norman** [comment]
I'd describe that behavior as a bug. But I just tried this with the following setup in a Rails 4.2.1 app with FriendlyId master:

```ruby
class City < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, :use => :slugged
  has_many :restaurants
end

class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :scope => :city, :use => [:slugged, :scoped, :history]

  belongs_to :city
end

ActiveRecord::Base.transaction do

  seattle = City.create! :name => 'Seattle'
  portland = City.create! :name => 'Portland'

  s1 = Restaurant.create! :name => 'Starbucks', :city => seattle
  puts s1.friendly_id

  s2 = Restaurant.create! :name => 'Starbucks', :city => portland
  puts s2.friendly_id
  s2.name = 'Starbugs'
  s2.slug = nil
  s2.save!
  puts s2.friendly_id

  p portland.restaurants.friendly.find('starbugs')
  p portland.restaurants.friendly.find('starbucks')

  raise ActiveRecord::Rollback
end
```

It seems to be working properly now - perhaps you were seeing this on an older version of the gem. I'm closing this issue for now, but if this is still affecting you (or anybody else) let me know.
