### ISSUE TITLE
Using `username` instead of `slug` as model attribute

### ISSUE THREAD

**Issue by ProGM** [norman/friendly_id#657]
Is it possible to change the referenced attribute in which friendly_id will save the slug?

For example, for my user, I'd like to call it `username`.

If not, do you think that you'll implement as future feature?

**Comment by ProGM** [comment]
Searching in the source code I found this:

```ruby
friendly_id :name, use: :slugged, slug_column: :username
```

It seems to work.

You should add this to the documentation... ;)

**Comment by norman** [comment]
No worries, there's a lot of documentation and sometimes it's hard to find the one sentence that explains how to do what you want to. Thanks for following up. I'd prefer not to add this to the README, I want to keep that for a high-level summary of the features, not for describing those kinds of specifics.
