### ISSUE TITLE
MySQL error. unknown column slug_candidates

### ISSUE THREAD

**Issue by isratmir** [norman/friendly_id#659]
Hello!
For some reason slug_candidates function participates in sql query as table parameter. 

In view it not renders as values:
![Screenshot]
(https://s3.amazonaws.com/fvd-data/notes/398403/1427877037-zbwS3b/screen.png)
```
Mysql2::Error: Unknown column 'table.slug_candidates' in 'where clause': SELECT `table`.* FROM `table` WHERE `table`.`slug_candidates` = '9477' ORDER BY `table`.`id` ASC LIMIT 1
```
```ruby
class Model < ActiveRecord::Base
  extend FriendlyId

friendly_id :slug_candidates, use: :finders

def slug_candidates
  [
     :id,
     [:id, :number]
  ]
end

def to_param
    "#{friendly_id}"
end

```

**Comment by norman** [comment]
Try use: [:finders, :slugged]

**Comment by isratmir** [comment]
OK, I see now. Slug column participates here.
Trying to implement functionality which allow to switch between random and sequential id and slug is unwanted here.
Thank you.
