### ISSUE TITLE
Breaks validates uniqueness: true

### ISSUE THREAD

**Issue by kingpalethe** [norman/friendly_id#660]
This seems to be the same issue as reported in the closed issue #152 

My Gem file:

``` ruby
ruby '2.2.0'
gem 'rails', '4.2.0'
gem 'friendly_id', '~> 5.1.0'
```

Here is my model code:

``` ruby
validates :title, presence: true, uniqueness: true
  extend FriendlyId
  friendly_id :title, :use => :slugged
```

The  

``` ruby
presence: true
```

validation works well, but my app does not apply the uniqueness validation... it will happily make model instances with duplicate :titles.

Elsewhere in my app, in models where I am not using Friendly_ID, I find the uniqueness validations work well. 

Also -- the slugging behavior and other features of Friendly_id do work as advertised.

thanks

**Comment by tylerwillingham** [comment]
I'm having what may be a similar problem. For me `validates :slug, presence: true, uniqueness: true` doesn't appear to work. I cannot verify the presence validation but the uniqueness validation is certainly not being respected.

**Comment by norman** [comment]
I've tried but have been unable to reproduce this. Did either of you ever get to the bottom of it?

**Comment by erlandsona** [comment]
Hey @norman, I'm building a simple rails api with basic token authentication and authorization with the pundit gem. I'm using your gem for friendly urls but I'm running into this same issue. Here's the code. I can't link to the repo because it's private but I'm not giving anything away here.

## config/initializers/friendly_id.rb
```ruby
# FriendlyId Global Configuration
FriendlyId.defaults do |config|
  # ## Reserved Words
  config.use :reserved

  config.reserved_words = %w(new edit index session login logout users admin
    stylesheets assets javascripts images)

  #  ## Friendly Finders

  config.use :finders
 
  # ## Slugs

  config.use :slugged

  #  ## Tips and Tricks
  #
  #  ### Controlling when slugs are generated

  config.use Module.new {
    def should_generate_new_friendly_id?
      friendly_slug_method = method(friendly_id_config.base)
      did_it_change = method(friendly_slug_method.call[0].to_s + "_changed?")
      slug.blank? || did_it_change.call
    end

    def default_candidates  # Added default candidates for use with slugged.
      [
        :name,
        [:name, :id]
      ]
    end
  }

end
```
I'm building the methods instead of sending them because I read somewhere it's faster??? Who knows, but it works for what I'm doin? The default_candidates just allows me to dry up my models a bit since in this particular app they all have a similar structure.

## client.rb
```ruby
class Client < ActiveRecord::Base
  include Tokenable

  extend FriendlyId # Be sure to check out the initializer for defaults.
  friendly_id :default_candidates

  after_initialize :set_default_role, if: :new_record?

  validates :auth_token, uniqueness: true
  validates :name, uniqueness: true, presence: true
  validates :slug, uniqueness: true, presence: true

  enum role: [:client, :admin]

  private

  def set_default_role
    self.role ||= :client
  end

end
```
## RSpec model_spec.rb
```ruby
describe Client, type: :model do
  before { @client = create :client }
  subject { @client }

  it { should be_valid }

  it { should respond_to(:name) }
  it { should validate_presence_of(:name) }
  it { should validate_uniqueness_of(:name) }

  it { should respond_to(:slug) }
  it { should validate_presence_of(:slug) }
  it { should validate_uniqueness_of(:slug) }

  it { should respond_to(:auth_token) }
  it { should validate_uniqueness_of(:auth_token) }

end
```
## Failure Message
```ruby
rspec spec/models/client_spec.rb
.....F...

Failures:

  1) Client should require slug to be set
     Failure/Error: it { should validate_presence_of(:slug) }
       Expected errors to include "can't be blank" when slug is set to nil,
       got no errors
     # ./spec/models/client_spec.rb:12:in `block (2 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:9:in `block (3 levels) in <top (required)>'
     # /austinerlandson.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /austinerlandson.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # /austinerlandson.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /austinerlandson.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `call'
     # /austinerlandson.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.5.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:8:in `block (2 levels) in <top (required)>'

Finished in 0.33867 seconds (files took 2.68 seconds to load)
9 examples, 1 failure

Failed examples:

rspec ./spec/models/client_spec.rb:12 # Client should require slug to be set
```
it fails because, from what I've read from your previous versions, slug generation happens on a before validation callback. But shouldn't that mean that the validation spec's should be working? Looking at the stack trace I'm thinking it's an issue with databasecleaner maybe but it's hard to tell? Adding pry calls or byebugs to shoulda-matchers to poke around is usually time consuming in these cases.

My uniqueness test is passing which I know is slightly different from what's happening in the title.

All this said, is it even relevant to be testing the slug column given that the gem is being tested on it's own? Meaning if the functionality is there and the plugin itself is vetted, isn't testing that it's working in my code similar to testing Devise?

I'm mainly asking because I'm wondering if I even need to test it?

**Comment by darrennix** [comment]
I have the same issue.

We allow users to manually change an existing slug because they often need to fine-tune publicly visible URLs (for job postings).

The Model looks like this:
```
class Job < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  validates :slug, uniqueness: {case_sensitive: false}, presence: true
  def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end
end
```

However, the uniqueness check does not fire and a user is able to generate a database error by entering an existing slug.

```
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_jobs_on_slug" DETAIL: Key (slug)=(customer-service-representative) already exists. : UPDATE "jobs" SET "slug" = $1, "updated_at" = $2 WHERE "jobs"."id" = $3
```

**Comment by johanb** [comment]
Experiencing a similar issue as @darrennix

**Comment by oyeanuj** [comment]
+1, same issue as @darrennix. @darrennix, @johanb did you find any solution to the problem?

**Comment by parndt** [comment]
@johanb did you ever solve this?

**Comment by oyeanuj** [comment]
@norman @parndt Any thoughts on how to possibly start solving for this?

**Comment by johanb** [comment]
@parndt sadly I did not

**Comment by marcamillion** [comment]
The issue I am having is similar-ish.

I have this:

```ruby
  extend FriendlyId
  friendly_id :name_and_school, use: :slugged

  def name_and_school
    "#{first_name} #{last_name} #{school.name}"
  end

```

But when I submit a form with no `first_name, last_name or school`, I get this error:

```
  Position Load (0.8ms)  SELECT "positions".* FROM "positions" WHERE 1=0
   (0.8ms)  BEGIN
   (0.6ms)  ROLLBACK
Completed 500 Internal Server Error in 51ms (ActiveRecord: 11.7ms)


NoMethodError - undefined method `name' for nil:NilClass:
  app/models/profile.rb:79:in `name_and_school'
  friendly_id (5.1.0) lib/friendly_id/slugged.rb:295:in `should_generate_new_friendly_id?'
  friendly_id (5.1.0) lib/friendly_id/slugged.rb:304:in `set_slug'
```

Which indicates that `name_and_school` is being executed before the validations are executed on this `profile` model.

Thoughts anyone?

**Comment by oyeanuj** [comment]
@parndt I know you are probably busy but if you have a moment to look - following up to see if you had any thoughts on what might be going on, and how to go about solving this or working around this? Thank you!

**Comment by parndt** [comment]
@oyeanuj if we had a spec that failed inside friendly_id codebase then it would make it much easier to figure out what is going on and write a patch for it.  You're right about me being busy.. I don't know when I'll next be able to free up the required time to look into it.

Do you have any interest in writing up a spec for us? Likely that you'd be able to grab most of the code/flow from https://github.com/norman/friendly_id/issues/660#issuecomment-175807230 and https://github.com/norman/friendly_id/issues/660#issuecomment-140138857

Thanks!

**Comment by oyeanuj** [comment]
@parndt Thank you for responding, and the pointers. I haven't contributed a spec before but I'll give it a shot!

**Comment by devanshu-m** [comment]
Hello, was anyone able to find a solution to this? I am unable to check uniqueness for my slug.

**Comment by oyeanuj** [comment]
@devanshu-m Not yet, I've been intending to write a spec (just haven't done it before). Maybe @marcamillion  above has found a fix. Otherwise, if you have a chance sooner than me, maybe creating those test specs would help.
