### ISSUE TITLE
friendly_id doesn't create slugs

### ISSUE THREAD

**Issue by pavankat** [norman/friendly_id#665]
```
gem "friendly_id", "~> 5.0.4"
```

Model:

```
class Topic < Activerecord::Base
  extend FriendlyId
  friendly_id :generated_slug, use: [:slugged, :history]

  def generated_slug
    title
  end
end
```

On save of the topic from the new action, the slug doesn't get created and on top of that, the URL goes to something like this: http://localhost:3000/topics/7 and the browser gives this: undefined method `friendly' for #

In addition, when I do this in the console:

```
Topic.create! title: "Joe Schmoe"
```

the slug column becomes nil.

**Comment by norman** [comment]
Have you restarted your app since you added FriendlyId?

**Comment by pavankat** [comment]
yes so many times and reloaded the console.

**Comment by norman** [comment]
And did you run the migration to create the slugs table?

**Comment by pavankat** [comment]
Topic.last.friendly_id gives an error: NoMethodError: undefined method `friendly_id' for nil:NilClass

I'm using friendly_id in other parts of my app, but have been manually creating the slugs myself, because the default behavior hasn't been working.

**Comment by norman** [comment]
> Topic.last.friendly_id gives an error: NoMethodError: undefined method `friendly_id' for nil:NilClass

Looks like you have no Topic records in your database.

> have been manually creating the slugs myself

What does "manually creating the slugs myself" entail precisely? Did you run the migration to create the slugs table?

> because the default behavior hasn't been working.

I think if FriendlyId were so broken that the basic setup failed in the way you described, we'd have **a lot ** of bug reports for this. It sounds very likely that this is a setup issue on your side. Please continue to investigate some more and if you find evidence of a problem with FriendlyId such as an unexpected incompatibility with a normal Rails setup, or a conflict with another gem, then we'll be happy to look into it.

**Comment by pavankat** [comment]
Hey norman, I have a slug column on the topic record, and I do have records for the topics table. 

By manually creating them, I meant that for our articles, I've put in a slug form field, so the admin can set the slug themselves. 

I'll keep looking. But I'm kind of lost.

**Comment by pavankat** [comment]
Ok this is interesting. I have a friendly_id_slugs table. Is that a reason why it might not be working?

Maybe I need to drop my slug column in my topics table?

**Comment by pavankat** [comment]
Turns out I had another model named the same that was overriding it.

**Comment by norman** [comment]
Glad you were able to resolve it, thanks for following up!
