### ISSUE TITLE
Works in console, not in controller

### ISSUE THREAD

**Issue by Svashta** [norman/friendly_id#666]
Hi,

i am pretty sure i am doing things right, but something is off.
I have this in controller:

    @location = Location.friendly.find(params[:id])

Model:

    extend FriendlyId
    friendly_id :name, use: :slugged

And the error says:

    Couldn't find Location with 'id'=my-super-name
    raise RecordNotFound, "Couldn't find #{name} with '#{primary_key}'=#{id}"

Yet, in console i get record just fine like this:

    Location.friendly.find('my-super-name')

Controller works when using

    friendly_id :name, use: [:slugged, :finders]

But i think it should work without it, too, as i am doing a friendly.find. :finders, as expected also work without friendy.find. - but i would like to control this...

I am on Rails 4.2.1 - Ruby 2.1.2
I have already searched around, but only found this one single [Stackoverflow](http://stackoverflow.com/questions/19732047/troubleshooting-friendly-id-w-rails-4-working-as-expected-in-rails-console-ge) topic without proper answer to solve this.

Thx

**Comment by norman** [comment]
Did you restart the server after adding FriendlyId? Try printing
`params.inspect` in the log or with `puts` to see what the id in the
controller is, any chance there's a space?

**Comment by Svashta** [comment]
Parameter comes through fine.

    {"id"=>"my-super-name"}

Looking through the log i've found the difference on select itself.
Finders:

    Location Load (1.1ms)  SELECT  `locations`.* FROM `locations` WHERE `locations`.`slug` = 'my-super-name'  ORDER BY `locations`.`id` ASC LIMIT 1

No finders (both time using friendly.find):

    Location Load (1.0ms)  SELECT  `locations`.* FROM `locations` WHERE `locations`.`id` = 0 LIMIT 1

**Comment by norman** [comment]
What version of FriendlyId are you using?

**Comment by Svashta** [comment]
friendly_id 5.1.0

**Comment by pavankat** [comment]
maybe try taking out finders?

```
friendly_id :name, use: [:slugged]
```

**Comment by Svashta** [comment]
No, that's the whole point > friendly.find doesn't work without :finders.
But with :finder, normal find works as friendly.find. No good.

**Comment by norman** [comment]
Would love to help with this, but without having your application code in front of me there's little I can do. If you can provide a sample app that reproduce there error I'd be more than happy to look into it.

**Comment by mesge** [comment]
Also seeing the same issue on rails 4.2.1

**Comment by nickyrasch** [comment]
Seem to have the same issues as well in 4.2.1 @mesge any luck?

**Comment by mesge** [comment]
Unfotunately not @nickyrasch. As a work around, I took [this advice](https://github.com/norman/friendly_id/issues/666#issuecomment-105112905) and removed finders. `find` now works as `friendly.find`.

**Comment by kememoda** [comment]
Look... using version '5.0.3' the error was "undefined method `primary' for #<ActiveRecord::ConnectionAdapters::Column:0x000000093ce2c8>.
I modified it "Room.friendly.find(params[:id])" for this "Room.friendly.find_by(id: params[:id])", and work.

Using version "5.1.0" the error is "raise RecordNotFound". I modified the same thing, but one functionality broken. So i recommend use version "5.0.3".

**Comment by kimrgrey** [comment]
Looks like this issue is staled and can be closed. `Xxx.friendly.find` works good both in controller and console by default. So, this problem should be somewhere else, but not in `friendly_id` itself. But, please, fill free to open issue again if you find additional details to clarify problem.

**Comment by Big-Gui** [comment]
This issue is closed. However, I had the same problem and the answer was that friendly doesn't seem to work with "load_and_authorize_resource".

**Comment by IsmaelEzequiel** [comment]
> This issue is closed. However, I had the same problem and the answer was that friendly doesn't seem to work with "load_and_authorize_resource".

YOU SAVED ME!!!
