### ISSUE TITLE
slugs generate for some but null for others

### ISSUE THREAD

**Issue by pavankat** [norman/friendly_id#668]
I ran this in a migration:

```
  	User.all.each do |u|
  		u.save
  	end
```

all the slugs were generated except 1. Even duplicate named records got slugs made with a uuid attached at the end.

However one of them, that was a duplicate didn't get made

```
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end
```

ruby '2.1.2'
gem 'rails', '4.1.4'
gem "friendly_id", "~> 5.0.4"

Any idea why?

**Comment by pavankat** [comment]
here's the data for the name and slug:

NAME SLUG
testuser3	testuser3
testuser2	testuser2
testuser123	testuser123
supercats	supercats
sfdfdfd	sfdfdfd
peterpan	peterpan
pavankatep	pavankatep
pavankatep	pavankatep-da9b4f51-0695-4385-ba55-274967ca37c7
pavankat	
pavankat	pavankat
orangeredrad	orangeredrad
meowsmeows	meowsmeows

**Comment by pavankat** [comment]
pavankat is missing a slug and is NULL in the postgresql database

**Comment by norman** [comment]
Sorry, there's not enough information here for me to help you. Also, this sounds like the sort of routine development issue you should be investigating yourself prior to opening a ticket on a bug tracker. Please investigate some more on your own and if you determine that there may be a bug in FriendlyId that's causing this, please post a bug report following [these guidelines](http://yourbugreportneedsmore.info/) at  I'll be happy to look at it.
