### ISSUE TITLE
Should slugify based on default_scope

### ISSUE THREAD

**Issue by silasb** [norman/friendly_id#672]
I'm having a weird issue, right now when we slugify a record it will ignore the default_scope of the record, so deleted records (default_scope is `deleted_at IS NULL`) will be searched when trying to create a record.

Is there a reason why it shouldn't follow the default_scope? or is there a method that I can override to apply default scope back to slug lookup query?

This is what I've tried:

overriding `exists_by_friendly_id?`

but this will eventually call https://github.com/norman/friendly_id/blob/master/lib/friendly_id/slugged.rb#L318 which will be false.

**Comment by norman** [comment]
Definitely a bug. FriendlyId uses `unscoped` to remove any order clauses when creating slugs - I think this should be changed to `reorder`.

**Comment by norman** [comment]
Hmm. Thinking this through some more I'm not sure this is a bug. If we made it use "reorder" rather than "unscoped," then if you put a unique index on the slug column then you'll get database errors when inserting a duplicate slug. I think the best strategy here would be to make the slug scoped by the `deleted_at` column, or set the slug to nil when marking a record as deleted.

**Comment by silasb** [comment]
I've tried `add_index :db_table, [:slug, :deleted_at], uniqueness: true` but the problem is that it will still find the deleted record when coming up with the unique slug consideration because we unscoped the default_scope.  I need to skip the deleted record so friendly_id thinks it doesn't exist so it doesn't try to create a token with a UUID at the end.

The solution that works for me is to remove the `unscoped` from `scope = self.class.base_class`.
 
Even if we remove the scoping from `scope = self.class.base_class` and have a unique index on the slug column wouldn't it still find the existing record successfully via the `scope.exists_by_friendly_id?(slug)` which would try different considerations? The only time this wouldn't work would be if we have a database index that doesn't scope the same attributes in default_scope.

**Comment by norman** [comment]
My concern here is that providing a general solution to this problem could cause more people more problems than leaving it alone; if people change the default scope or remove it, they'll likely have hell to pay with non-unique slugs being generated. I think this is a case where the logic needed for your application is totally valid and sensible, but perhaps should not be incorporated at the library level.

I actually don't feel too strongly about that though. I need to think about it some more.

> The solution that works for me is to remove the unscoped from scope = self.class.base_class.

To address your immediate concern - perhaps in this case overriding the `scope_for_slug_generator` method really is in fact be the best alternative; not sure how you have done this in your code yet, but you can do it in a very compatible way by merging the scope FriendlyId generates with your default scope like this:

```ruby
private

def scope_for_slug_generator
  super.merge(Person.all)
end
```
