### ISSUE TITLE
Fetch all objects, ignoring scopes

### ISSUE THREAD

**Issue by Linuus** [norman/friendly_id#675]
Hi

I have a model, `Article`, which has friendlyid with the _history_ module. Now I want to scope the slugs on the department it belongs to. But before I deploy I need to make sure it can redirect the old urls.

So, if I go to `/articles/foobar` I want to fetch all articles which has the `foobar` slug, both right now and from history, ignoring the scope. Then I can check the fetched articles and redirect if I need to to something like `/departments/foo/articles/foobar`.

Is it possible to fetch all articles with a certain slug, ignoring the scope, including history?

**Comment by norman** [comment]
Sure, you can search the FriendlyId::Slug model like any other Active Record model, and then access its "sluggable" property to get the model it belongs to.
