### ISSUE TITLE
Friendly_id and Rails 4.2 URL helpers problem

### ISSUE THREAD

**Issue by kozhin** [norman/friendly_id#676]
Hi there!

I have a problem with Friendly_id. It places dots instead of slashes when used with Rails model's URL helper.

Code:
```
# index.html.erb
<% @articles.each do |article| %>
    <a target="_blank" href="http://vkontakte.ru/share.php?url=<%= articles_url(article) %>" title="<%= article.title %>"><i class="fa fa-vk"></i></a>
<% end %>
```

Result:
```
<a target="_blank" href="http://vkontakte.ru/share.php?url=http://localhost:3000/articles.just-a-test-article" title="Just a test article"><i class="fa fa-vk"></i></a>
```

The URL generated by **articles_url(article)** is
**http://localhost:3000/articles.just-a-test-article**
but it should be
**http://localhost:3000/articles/just-a-test-article**

If I did something in a wrong way, please, correct me.

**Comment by norman** [comment]
It's almost certainly something in your app, but you haven't given information for me to be able help you. Please see the info here about how to ask for help in open source projects: http://yourbugreportneedsmore.info/

**Comment by kozhin** [comment]
Hi!
I've forgotten to write back.
The problem was in the helper method I used.

I used
```<%= articles_url(article) %>```
Must be
```<%= article_url(article) %>```

My bad. Sorry!

**Comment by norman** [comment]
No problem, thanks for following up, and I'm glad you found the source of your problem!
