### ISSUE TITLE
 undefined method sequence_separator=  (NoMethodError)

### ISSUE THREAD

**Issue by januszm** [norman/friendly_id#678]
I keep getting this error whenever I try to set the deault configuration for the sequence_separator in the initialiser.

Here's the fragment of my initialiser, which is the default generated one:

    FriendlyId.defaults do |config|
        # When FriendlyId can not generate a unique ID from your base method, it appends
        # a UUID, separated by a single dash. You can configure the character used as the
        # separator. If you're upgrading from FriendlyId 4, you may wish to replace this
        # with two dashes.
        #
        config.sequence_separator = '--'
        #

I've noticed that the attr_writer is present in the Slugged module in

    module Configuration
      attr_writer :slug_column, :sequence_separator

But it is it the right place? Initialiser sets FriendlyId.defaults, there's no such writer in FriendlyId::Configuration or in Base module. Also, id doesn't work if I try to set it in defaults using

    config.sequence_separator '--'

or

    config[:sequence_separator] = '--'

This fragment should be removed from or updated in the default, generated initialiser, or a proper attr_writer should be added in right place.

**Comment by norman** [comment]
Please see #650.

**Comment by k3vout** [comment]
Check this solution: https://stackoverflow.com/a/30323207/23497576
