### ISSUE TITLE
Issue with url params / query string after the friendly-id slug in URL

### ISSUE THREAD

**Issue by jgrannas** [norman/friendly_id#681]
So google shopping appends a variable to the end of my URL:

For example:
http://www.url.com/products/my-slug-name-here?gclid=Cj0KEQjwn86sBRDroPiR0LrSzNYBEiQAzOaSYCZzH3azHiiasrmOInpJm_pjhljXCrBurUwoKkvObr4aAtPF8P8HAQ

When you click this link from the google shopping page, it results in a 404 error... however, if you refresh the page with the URL in place, it then loads the page fine...

Any ideas as to what could be causing this odd issue? What's really weird is I can't seem to duplicate this in production by creating a direct link to a friendly-id page with this param on the end.

gemfile
```
gem 'friendly_id', '~> 5.0.0'
```

controller
```
def show
    @product = Product.friendly.find(params[:id])
end
```

model
```
class Product
    ...
    extend FriendlyId
    friendly_id :slug_candidates, :use => [:slugged, :history, :finders]
    ...
end
```

**Comment by norman** [comment]
Sorry, never seen that problem before. I very much doubt it's FriendlyId, it's much more likely an error in your code. Try looking in your logs for a stack trace, or SQL statement, or use puts to print out the parameters and find out what's going on.
