### ISSUE TITLE
Overriding should_generate_new_friendly_id? in initializer doesn't work when using Slugged

### ISSUE THREAD

**Issue by strika** [norman/friendly_id#682]
We're using FriendlyId on several projects for a long time. When we upgraded from version 4 to version 5, we wanted to keep the old behavior of regenerating a slug when the value of the column that the slug is based on changes.

We followed instructions in the [FriendlyId initalizer](https://github.com/norman/friendly_id/blob/b6b6c004890ae3558a8ee19cc004a1456d9d0fff/lib/friendly_id/initializer.rb#L70-L80). But, this didn't work. After some debugging, we concluded that this is related to the fact that the same model was using Slugged module that also defines `should_generate_new_friendly_id?` [method](https://github.com/norman/friendly_id/blob/b6b6c004890ae3558a8ee19cc004a1456d9d0fff/lib/friendly_id/initializer.rb#L70-L80). Problem was that Slugged module was included after the anonymous module defined in the initializer, so it overrides the `should_generate_new_friendly_id?` method from the anonymous module.

This should be clearly explained or, if possible, anonymous modules defined by a user in the initializer should be included last.

Thank you.

**Comment by edwardmp** [comment]
Good catch, certainly a valid point. But what to do if you don't to set `config.use :slugged` i.e. because not every model is slugged?
