### ISSUE TITLE
Add support for returning ActiveRecord::Relation instead of running the query immediately.

### ISSUE THREAD

**Issue by ShimShtein** [norman/friendly_id#683]
Consider code like this:
``` Ruby
query = Posts.where(has_comments: true)

if look_by_author
  query = query.where(author: my_author)
end

query = query.sort(:relevancy)
```
It would be nice if I could use a friendly_id in the second `query` assignment, assuming I have marked the `author` field to use friendly_id.

**Comment by norman** [comment]
You can do:

```
where(slug: 'foobar')
```

This won't use slug history but if you're not using that, then this would accomplish what you're asking for.

I don't understand why you want this functionality though. You can do `query.friendly.find('foobar')` at the very end if you want to build up scopes iteratively; what's the difference with doing it earlier or leaving it for last?

**Comment by ShimShtein** [comment]
I have over-simplified the example.
I will try to describe the user story that I had in mind for this feature:

1. We have hierarchical resources: Multiple blogs which have multiple posts. This implies urls of type http://localhost/blogs/_my-very-interesting-blog_/posts/_post-about-friendly-id_
2. The same resource could be accessed directly i.e.: http://localhost/posts/_post-about-friendly-id_
3. I want to enable access by id in both cases i.e: http://localhost/blogs/_1111_/posts/_555_ should be valid too.
4. I want to minimize the number of queries in order to get the valid post record. That means I don't   want to perform extra query for getting the parent blog record (if it's present), and filter based on that object.

So schematically the code should look like this:

``` Ruby
base_query = Posts.all

if (parent_blog)
  base_query = base_query.joins(:blogs).find(parent_blog)
end

#do some other modifications to the query
# ...

current_post = base_query.find(current_post_param)
```
It's only a schematic, if you are interested in the real world scenario, I would gladly walk you through our code. I have created a simple workaround for this issue in this PR: https://github.com/theforeman/foreman/pull/2099. Take a look on the following methods: [`#resource_scope`](https://github.com/theforeman/foreman/pull/2099/files#diff-b4f92b4e361ffab4fbb91c68eb3f77bbL44), [`#parent_scope`](https://github.com/theforeman/foreman/pull/2099/files#diff-b4f92b4e361ffab4fbb91c68eb3f77bbR49) and the actual scope implementation in lines starting with [L269](https://github.com/theforeman/foreman/pull/2099/files#diff-b4f92b4e361ffab4fbb91c68eb3f77bbR269). It is a generic utility code for all resources exposed by our system, so it brings another difficulty about finding out the proper types, but I think the heart of it is the scheme that I have already described.

About using slugs: I am not sure it gives us a solution for requirement 3 in the user story I have described.

**Comment by norman** [comment]
I still don't understand what the real-world limitation is in FriendlyId here. If you wish to pull up a single record, why is it undesirable to leave the `find` until last?

To be perfectly frank, I just don't have a free hour or two to dig into your application to discover if there's some place I could make a change to benefit your codebase. If you want us to change something, the burden is on you to make a coherent argument as to why you think it's beneficial. I still don't understand what you're asking us to do, or why.

**Comment by norman** [comment]
Ok, I'm a few sips more into my coffee here in the Buenos Aires winter morning. Sorry if my previous response was a little grumpy. Perhaps you could use:

```
if parent_blog.friendly_id?
  base_query = base_query.joins(:blogs).where("blogs.slug = ?", parent_blog)
else
  base_query = base_query.joins(:blogs).where("blogs.id = ?", parent_blog)
end
```

Or is this not an option because you want slugs or ids, **plus** history?

Note that internally FriendlyId is going to perform multiple queries if you're using history - so you're not necessarily going to get this in a single query with FriendlyId anyway.

In my experience I've found it's quite often faster to perform a find by id rather than a join - Active Record does that for eager loading associations. You know your application better than I do so perhaps you've already looked at the difference between doing it in a single query versus doing a separate lookup, but if you haven't then you should.

In any event I'm highly skeptical about making a change  here but perhaps I'm still not understanding everything.

**Comment by ShimShtein** [comment]
> Ok, I'm a few sips more into my coffee here in the Buenos Aires winter morning. 
We all have those days :) 

Right now we don't use a slug column, perhaps it's because we didn't upgrade to 5.x yet?
> Or is this not an option because you want slugs or ids, plus history?

We don't use history right now, so it shouldn't be a problem.

> In my experience I've found it's quite often faster to perform an extra find by id rather than a join

My problem is that the parent model is pretty chubby, and takes time and effort to bring. So double lookup is not a very good option for us, and we prefer the join approach.

The `slug` option makes my life a bit easier, as I can use it instead of trying to figure out which column contains the slug.

Anyway I thing that for friendly_id it would be a beneficial step to move to a lazy-evaluated design, as it is already the case for native ActiveRecord utilities.

**Comment by norman** [comment]
> Right now we don't use a slug column, perhaps it's because we didn't upgrade to 5.x yet?

Are you on version 3.x? You need a slug column as from version 4, which itself is already a couple years old.

> My problem is that the parent model is pretty chubby, and takes time and effort to bring. So double lookup is not a very good option for us, and we prefer the join approach.

Use `pluck` to pull up only the id - Active Record will emit an optimized query. It doesn't matter how many columns your table has or how many rows are in your table, `SELECT id FROM table WHERE slug = ?` is going to be very fast as long as there's an index on the slug column, and won't load the entire model, it will just return the id.

> Anyway I thing that for friendly_id it would be a beneficial step to move to a lazy-evaluated design, as it is already the case for native ActiveRecord utilities.

The purpose of FriendlyId is to extend `find` not `where`. In Active Record, `find` does not return a scope, it returns a model, and FriendlyId doesn't change that. So you're asking for a completely new feature - extending `where` as well as `find`. As far as I can understand the only useful purpose of this feature is to permit joins against models using FriendlyId, but my experience with this library tells me this is less optimal than doing a separate SELECT. For that reason, I don't intend to implement this, but if you want to, I'd consider adding it if you can prove to me that it's more optimal than the strategy I've suggested. I don't think you'll be able to do that, but I've been wrong before.

However I recommend you try fixing this in your own application by using a separate query with `pluck`  as I've described here prior to attempting to implement this. I'm quite certain you'll find it easier and better.
