### ISSUE TITLE
Cannot generate slugs from console

### ISSUE THREAD

**Issue by jgrannas** [norman/friendly_id#685]
gem "friendly_id", "5.0.2"

I have some existing records I am trying to update in the rails console

```
Timeslip.where(slug:nil).each do |t|
    puts t.should_generate_new_friendly_id?
    t.save
end
```
this returns true for the should_generate... but it doesn't save the slugs.

I also tried
```
Timeslip.where(slug:nil).first.save(validate:false)
```
which returns true, but the record still has no slug when i get the first one again.... help!

**Comment by kimrgrey** [comment]
Hi, @jgrannas. Sorry for such delay! May be you just forgot to add `slugged` module to use list in your module? Anyway, you can alway try to call `model.set_slug` and see what's happening. Hope, this advise will be helpful.
