### ISSUE TITLE
Slug in model is blank when using Friendly_id 5.1.0 & Globalize

### ISSUE THREAD

**Issue by kevin-jj** [norman/friendly_id#686]
After add a column slug to model  friendly_id & globalize works well, but why slug in model is blank?

**Comment by kevin-jj** [comment]
After add a column slug to model  it works well, but why slug in model is blank?

**Comment by ouelletv** [comment]
Im having the same problem. Found any workaround?

**Comment by kevin-jj** [comment]
@ouelletv I removed the slug in the model and only remain the slug column in translation table.  That will result in you only use ```ruby Model.friendly.find(params[:id]) to load record```.

**Comment by ouelletv** [comment]
I tried to do the same but friendly_id :history addon seems to require a :slug column in the parent table.

**Comment by kevin-jj** [comment]
@ouelletv  if you get friendly_id:history setup,  history table would only save the initial slug but all updated slug.

**Comment by kevin-jj** [comment]
@ouelletv  Can the history table update the slug when slugs change in Rails4.2.3?

As I get :history setup,  and config 

def should_generate_new_friendly_id?
     slug.blank? || name_changed?
end

It raises exception that undefinded method name_changed?
