### ISSUE TITLE
`parameterized` seems to not be called on `friendly_id` method

### ISSUE THREAD

**Issue by novikserg** [norman/friendly_id#687]
Hey there! Thanks for a great gem.

I am using Rails 4.2.3 and ruby 2.1.1p76. When using `friendly_id` with custom id-formatting method, it doesn't seem to parameterize my strings (and it's stated as example multiple times in README, for example, for "The Plaza Diner" examples, and it's also stated in comments within gem that `parameterized` is called). 

Here is the spec that fails for me:

```ruby
require "helper"

class City < ActiveRecord::Base
  extend FriendlyId
  friendly_id :custom_name_method

  private

  def custom_name_method
    "whatever #{name}"
  end
end

class ScopedHistoryTest < TestCaseClass
  test "should find old scoped slugs" do
    city = City.create!(name: 'Test Name')
    assert_equal(city.friendly_id, "whatever-test-name")
  end
end
```

It fails with 
```
  1) Failure:
ScopedHistoryTest#test_should_find_old_scoped_slugs [/Users/konnigun/opensource/friendly_id/test/history_test.rb:17]:
Expected: "whatever Test Name"
  Actual: "whatever-test-name"
```

Even more, if I just `friendly_id :name` without any custom method - it also returns uppercase string with spaces in it. What am I possibly doing wrong? Is it expected behavior? 
Thanks!

**Comment by norman** [comment]
Try `friendly_id :custom_name_method, use: :slugged`.
