### ISSUE TITLE
Keep the clean slug id number when resolving slug conflict

### ISSUE THREAD

**Issue by casertap** [norman/friendly_id#689]
I would like to keep the old behavior of having a simple sequence number to resolve slug conflit and not the ugly UUID.

Is there an option to do just that?
If not I feel that this should be implemented.

**Comment by norman** [comment]
That's in 5.2.0.beta.1 on Rubygems, or master in this repo.

**Comment by casertap** [comment]
great, what is the name of the option please?

**Comment by norman** [comment]
Sorry it's not documented yet. Please look in the recently closed pull
requests or read the source, I'm on vacation and have limited computer
access right now.

**Comment by andreibondarev** [comment]
@casertap Have you figured out the answer to this yet?
