### ISSUE TITLE
Generate slug-6f70c453-2e3d-40a1-93cc-f44d0b9af70c

### ISSUE THREAD

**Issue by laerciocrestani** [norman/friendly_id#690]
Hello everybody, when I paste some information in the input I generates a kind of token in SLUG.

when I necklace on input: Input Normal
records in the database: input-regular-6f70c453-2e3d-40a1-93cc-f44d0b9af70c
```
class Panel :: Category <ActiveRecord :: Base
....
  
   extend FriendlyId
   friendly_id: name, use: [: slugged,: finders]
  
   private
  
     def should_generate_new_friendly_id?
       slug.blank? || Nome_changed?
     end
end
```
Only when I cut and paste some content inside the input that happens, someone help me?

**Comment by laerciocrestani** [comment]
I`m using a nested with acts_as_nested_set GEM.
When slug name is equal, generate a token, see the pic.
![captura de tela 2015-08-02 as 21 11 42](https://cloud.githubusercontent.com/assets/1430869/9028804/41be1c40-395b-11e5-8e2a-9e33e2fec1ec.png)

**Comment by laerciocrestani** [comment]
ID:5 and ID: 14, for example.

**Comment by norman** [comment]
This is covered [in the Guide](http://norman.github.io/friendly_id/file.Guide.html#Uniqueness), please take a look.

**Comment by laerciocrestani** [comment]
Ok norman, thank you!
