### ISSUE TITLE
Translated slugs with Simple I18n

### ISSUE THREAD

**Issue by cimm** [norman/friendly_id#695]
I have FriendlyId working with a simple `slug` column on my Blog::Post model. Now I would like to translate the slugs in different languages but I can't get it to work. I removed the `slug` column and added a `slug_en`, `slug_fr` and `slug_nl` one to the same table.

```ruby
create_table "blog_posts", force: :cascade do |t|
  t.boolean  "draft",        limit: 1
  t.datetime "published_at"
  t.string   "slug_en",      limit: 255
  t.string   "slug_fr",      limit: 255
  t.string   "slug_nl",      limit: 255
end
```
I didn't change the model:

```ruby
class Blog::Post < ActiveRecord::Base
  extend FriendlyId
  self.table_name = 'blog_posts'
  friendly_id :title, use: :slugged
  translates :title, :body
end
```
But a simple:
```ruby
I18n.locale = :en
Blog::Post.find("star-wars")
```
now throws: `undefined method 'slug' for #<Blog::Post:0x007f9494296f50>`
Surely I am missing something... thank you!

**Comment by norman** [comment]
Try 

```ruby
Blog::Post.friendly.find("star-wars")
```

or use the `:finders` addon if you don't want to have to explicitly use the `friendly` scope:

```ruby
friendly_id :title, use: [:slugged, :finders]
```

**Comment by cimm** [comment]
Thank you norman. Tried your suggestions but it doesn't work.

In IRB:

```
> Blog::Post.friendly.find("star-wars")
  Blog::Post Load (0.4ms)  SELECT  `blog_posts`.* FROM `blog_posts` WHERE `blog_posts`.`slug` = 'star-wars'  ORDER BY `blog_posts`.`id` ASC LIMIT 1
```

Same when I try with the finder. The generated query looks for the slug column which doesn't exist, that seems wrong, isn't it? I feel ActiveRecord just doesn't understand how to use Simple I18n.  We are using globalize, I'll try FriendlyId Globalize and see if that helps.

**Comment by norman** [comment]
You need to add a slug column. I'd suggest reading the guide from the very
beginning, sounds like you maybe didn't do that.

**Comment by cimm** [comment]
You are right. Find a comment somewhere saying the `slug` column wasn't needed. Sorry about that and thank you for the superb support!
