### ISSUE TITLE
Module method from config is not overriding the default behavior.

### ISSUE THREAD

**Issue by faucct** [norman/friendly_id#696]
The example you have in initializers/friendly_id.rb does not work: this method is just not getting called.

```
config.use Module.new {
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
}
```

Works great though if I include it in "friendly_id" method call at my model.

```
friendly_id :name, use: Module.new {
                     def should_generate_new_friendly_id?
                       slug.blank? || super
                     end
                   }
```

**Comment by abhishekbose87** [comment]
Hi @faucct 

What I think is happening (and I might be wrong) is that slugged module has the method "should_generate_new_friendly_id?" which is overriding your custom method since your including :slugged module at model level.

Instead when I tried the following, the custom method is called.

```
config.use :slugged
config.use Module.new {
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
} 
```
And in the model just have
```
friendly_id :name
```

**Comment by abhishekbose87** [comment]
Hi @norman .. we have a similar issue https://github.com/norman/friendly_id/issues/682 open. 

IMO we should have the method(defined in initializers/friendly_id.rb) overrride the one mentioned in slugged module.
Does this warrant a fix. What do you think ?

**Comment by norman** [comment]
@abhishekbose87 I think we should just fix the example in the initializer. We should add the `use :slugged` before the Module definition as you discovered, and add a line documenting why you need to have that.
