### ISSUE TITLE
Minor mistake in guide: History controller example

### ISSUE THREAD

**Issue by AhmedBelal** [norman/friendly_id#699]
https://github.com/norman/friendly_id/blob/0c3f70f528bfcae25dc7084a5b71123e5470ad8a/lib/friendly_id/history.rb#L44

`@post = Post.find params[:id]` should be `@post = Post.friendly.find params[:id]` in versions 5.0 and above.

**Comment by kimrgrey** [comment]
Thank you for your contribution! This bug has been fixed by this commit: https://github.com/norman/friendly_id/commit/8feb3ba9e3eddabaec9357254e3798e5537eb180.
