### ISSUE TITLE
gem should not allow users to choose names which are a number

### ISSUE THREAD

**Issue by esromneb** [norman/friendly_id#701]
If a user (user 25) has their name field set to nil, their user id will still work as a friendly id.  If a new user (user 26) sets their name to the string "25" he will override the route for the first user.

Users should not be allowed to pick vanity names which are numbers

**Comment by norman** [comment]
I see that as application logic, not library logic. Some applications specifically need to allow numeric slugs as strings. This is discussed in the documentation.

FriendlyId and Rails already offer many ways to deal with this situation, some of the approaches you might take are:

* Don't allow nil user names.
* Use validations to disallow user names such as "25".
* Use `Mode.find_by_friendly_id` to ensure you're always looking up users by the friendly id.
