### ISSUE TITLE
Release 5.2.0

### ISSUE THREAD

**Issue by pabloh** [norman/friendly_id#702]
I could really use the FriendlyId 4.x-style sequential slugs feature on a project right now.
Is there any chance version 5.2 will be released soon?.

**Comment by norman** [comment]
There's currently no release timeline, but you could help us get it out sooner by trying the feature and letting us know how it works for you.

**Comment by pabloh** [comment]
@norman, I've been using firendly_id master in production for a while as you suggested without noticing any problems (besides what I already fixed with #704). Do you think you can merge it and release soon?.

**Comment by kimrgrey** [comment]
Hi, @norman! What about this PR from @pabloh and new release? We are using `master` at the moment, but it looks like great idea to fix known issues and make new release.
