### ISSUE TITLE
Way to add scope to uniqueness conflicts?

### ISSUE THREAD

**Issue by brchristian** [norman/friendly_id#709]
I'm working on a project where user names will be part of the URL, so I don't need my slugs to be globally unique, only unique per user.

Rails gives me a way to check this as a validation:

    validates :slug, uniqueness: {scope: :user}

But I'm still seeing the friendly_id gem append UUIDs to these slugs. Is there a way for friendly_id to accept a uniqueness scope, similar to the `validates` method?

**Comment by norman** [comment]
Have you looked at the "scoped" functionality? Does that not do what you
need?

**Comment by brchristian** [comment]
@norman Ah, it does precisely what I need! Somehow I missed that in the docs. Sorry and many thanks, cheers!
