### ISSUE TITLE
Is it possible to speed up slug creation on a large table?

### ISSUE THREAD

**Issue by slead** [norman/friendly_id#711]
I have a table of 18 million addresses, and I'm using a composite slug comprising the address and locality:
```
extend FriendlyId
friendly_id :slug_candidates, use: :slugged
def slug_candidates
 [
  [:FullAddress, :Locality],
 ]
end
```
I'm trying to create slugs using `Address.find_each(&:save)` in a Rails console, which is taking around 1 second per feature, which means it'll take a long time to finish. Are there any tips for speeding this up?

I thought about calculating the slug manually using SQL in the database, but I don't know how to handle duplicate addresses. 

Thanks for any tips, and for writing such a useful gem!

**Comment by kimrgrey** [comment]
Hi, @slead! Sorry for such delay! Are you still have this problem? Generating of slugs for each model one by one will have some overhead on conflicts check. It's definitely possible to fill slugs faster manually. Did you find useful solution? For example, you can try to setup slugs with SQL query, find out how many conflicts you will have and then fix this conflicts by second query that will add digital counter to slugs.

**Comment by slead** [comment]
Thanks for the reply - I let the slug creation run in the background so I didn't find a workaround in the end.
