### ISSUE TITLE
undefined method `relation' for class `Class'

### ISSUE THREAD

**Issue by peddinti** [norman/friendly_id#712]
I am using Friendly id for the user class and i am getting the following error.
NameError: undefined method `relation' for class `Class'
from /Users/ViswaMani/.rvm/gems/ruby-2.2.2@futura/gems/friendly_id-4.0.10.1/lib/friendly_id.rb:82:in `singleton class'

class User
  extend FriendlyId
.....
friendly_id :handle, use: :slugged
.....
def handle
    [
        [:first_name, :last_name],
        [:first_name, :last_name, :major],
        [:first_name, :last_name, :major, :degree]
    ]
  end

There is no relation between models. Not sure what is happening

**Comment by kimrgrey** [comment]
@peddinti, hi! Thank you for your feedback! Is this problem is still occurs? Could you please clarify which version of friendly_id are you using? It would be easier to find and fix the problem if you provide some test that will reproduce an error. You can use following snippet as an example:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.5'
  gem 'sqlite3'
  gem 'friendly_id', '~> 5.1.0', :require => false
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'friendly_id'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true  do |t|
    t.string :title
    t.string :slug
  end

  create_table :friendly_id_slugs do |t|
    t.string   :slug,           :null => false
    t.integer  :sluggable_id,   :null => false
    t.string   :sluggable_type, :limit => 50
    t.string   :scope
    t.datetime :created_at
  end

  add_index :friendly_id_slugs, :sluggable_id
  add_index :friendly_id_slugs, [:slug, :sluggable_type], length: { slug: 140, sluggable_type: 50 }
  add_index :friendly_id_slugs, [:slug, :sluggable_type, :scope], length: { slug: 70, sluggable_type: 50, scope: 70 }, unique: true
  add_index :friendly_id_slugs, :sluggable_type
end

class Post < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, :use => [ :slugged ]

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(:title => "My Post")
    assert_equal post, Post.friendly.find("my-post")
  end
end

```

**Comment by peddinti** [comment]
Sorry for late reply. I am still having this issue. the version i am using is 4.0.10.1 

The model looks as follows
require 'bcrypt'
require 'autoinc'
class User
  extend FriendlyId
  include Mongoid::Document
  include Mongoid::Autoinc
  include BCrypt
  include UsersHelper
  include UsersManager
  include MeedPointsTransactionManager
  include LinkHelper

  field :_id, type: String, default: -> { email }
  friendly_id :handle, use: :slugged
  field :email, type: String
  field :password_hash, :type => String
  field :first_name, type: String
  field :primary_email, type: String
  field :last_name, type: String
  field :facebook_handle, type: String
  field :twitter_handle, type: String
  field :github_handle, type: String
  field :gender, type: String
  field :degree, type: String
  field :major, type: String
  field :major_id, type: String
  field :minor, type: String
  field :minor_id, type: String
  field :fb_friend_hash, type: String
  field :year, type: String
  field :active, type: Boolean
  field :alumni, type: Boolean
  field :badge, type: String, default: -> { UserBadgeTypes::NEW_HIRE }
  field :gpa, type: BigDecimal
  field :create_dttm, type: Time, default: 1.year.ago
  field :last_login_dttm, type: Time
  field :phone_number, type: String
  field :location, type: String
  field :street_address, type: String
  field :zipcode, type: String
  field :t_size, type: String
  field :image_url, type: String, :default => DEFAULT_IMAGE
  field :small_image_url, type: String, :default => DEFAULT_SMALL_IMAGE
  field :large_image_url, type: String, :default => DEFAULT_LARGE_IMAGE
  field :meta_data, type: Hash
  field :meed_points, type: Integer, default: -> { 25 }
  field :headline, type: String
  field :bio, type: String
  field :waitlist_no, type: Integer
  field :meediorite, type: Boolean, :default => false
  field :major_types, type: Array
  field :current_company, type: String
  field :default_cids, type: Array
  field :company_ids, type: Array
  field :fb_handle, type: String
  field :school_id, type: String
  field :school_ids, type: Array
  field :other_school_ids, type: Array
  field :twitter_handle, type: String
  field :follower_count, type: Integer, :default => 0
  field :resume_url, type: String
  field :verified_current_company, type: Boolean, default: false

  has_one :profile, foreign_key: "handle", primary_key: 'handle'
  # User.exists(current_company: true).each { |u| u.update_attributes verified_current_company: true, company: Company.find_by(name: u.current_company); u.save }
  belongs_to :company, index: true
  has_many :job_applicants, foreign_key: "handle", primary_key: 'handle'

  increments :waitlist_no, auto: false, seed: 200

  attr_accessor :password, :password_confirmation
  attr_protected :password_hash
  attr_accessible :handle, :email,
                  :first_name, :last_name,
                  :gender, :year,
                  :default_cids,
                  :major, :major_id,
                  :minor, :minor_id,
                  :badge, :company_ids, :current_company,
                  :headline, :bio, :follower_count,
                  :major_types,
                  :fb_handle, :github_handle, :facebook_handle, :twitter_handle,
                  :twitter_handle,
                  :school_id, :school_ids, :other_school_ids,
                  :degree, :active,
                  :alumni, :location,
                  :gpa, :primary_email,
                  :phone_number, :last_login_dttm, :image_url, :small_image_url, :large_image_url,
                  :company, :verified_current_company,
                  :meta_data, :meed_points, :meediorite, :fb_friend_hash, :resume_url

  set_callback(:save, :after) do |document|
    if :first_name_changed? || :last_name_changed? || :major_changed
      SitemapPingerWorker.perform_async(get_user_profile_url(handle))
    end
    if :first_name_changed? || :last_name_changed? || :major_changed? || :minor_changed? || :badge_changed? ||
        :degree_changed? || :verfied_current_company_changed? || :current_company_changed? || :year_changed? ||
        :image_url_changed?
      IntercomUpdateUserWorker.perform_async(document.handle)
    end
  end

  def authenticate(email, password)
   end

  def is_alumni?
   # DELETED
  end

  def school
   # DELETED
  end

  def handle
    [
        :email,
        [:first_name, :last_name],
        [:first_name, :last_name, :degree]
    ]
  end

  def name
   # DELETED
  end

  def test_user?
    # DELETED
  end

  def is_admin?
    # DELETED
  end

  def equals?(user)
   # DELETED
  end

  def password_correct?(user_email, password)
    # DELETED
  end

  def is_default_image?
    # DELETED
  end

  def profile_url
    # DELETED
  end

  def auth_profile_url
    # DELETED
  end

  def missing_basic_info?
    # DELETED
  end

  def as_json(options={})
    # DELETED
  end

  def is_meediorite?
    # DELETED
  end

  def is_moderator?
    # DELETED
  end

  def self.group_by(field, format = 'day', limit = 7)
    # DELETED
  end

  def add_waitlist_no()
    assign!(:waitlist_no) if waitlist_no.blank?
  end

  protected

  def create_remember_token
    # DELETED
  end

end
