### ISSUE TITLE
Error: uninitialized constant FriendlyId::ActiveRecord

### ISSUE THREAD

**Issue by BorisBresciani** [norman/friendly_id#714]
Hey, i have this error when i starting my rails server:

gems/friendly_id-5.1.0/lib/friendly_id.rb:56:in `<module:FriendlyId>': uninitialized constant FriendlyId::ActiveRecord (NameError)

Thanks !

Boris

**Comment by 1aurabrown** [comment]
@BorisBresciani Hi, I am having this same problem. How did you solve it?

**Comment by nuheluxulu** [comment]
Same issue. Had to restart my rails server.

**Comment by kumarn33** [comment]
I am getting this error with friendly id 5.1.0 and rails 5.1.4
