### ISSUE TITLE
Attempt to create empty slug despite data in candidate field

### ISSUE THREAD

**Issue by kbroderick** [norman/friendly_id#727]
I've got an app that was recently updated to run on Rails 4.2.5 (previously on Rails 3.1), and we're getting an odd record-creation issue with some slugs. More specifically, the app seems to want to create empty slugs:

```
D, [2016-01-14T12:02:58.309457 #25646] DEBUG -- :   SQL (1.2ms)  INSERT INTO `base_ads` (`business_name`, `edition_id`, `category_id`, `grid_number`, `notes`, `ad_copy`, `location_override`, `video_url`, `client_id`, `photos_label`, `pdfs_label`, `ad_total`, `facebook_id`, `custom_price_explaination`, `slug`, `approved_by`, `created_at`, `updated_at`) VALUES ('Bill Green Jewelers DUDE', 1548, 7116, '', '', '<br />', '', '', 8677, '', '', 0, '', '', '', 'Kevin Broderick', '2016-01-14 17:02:58', '2016-01-14 17:02:58')
D, [2016-01-14T12:02:58.314923 #25646] DEBUG -- :   CityTag Load (4.3ms)  SELECT `city_tags`.* FROM `city_tags` INNER JOIN `city_taggables` ON `city_tags`.`id` = `city_taggables`.`city_tag_id` WHERE `city_taggables`.`city_taggable_id` = 208013 AND `city_taggables`.`city_taggable_type` = 'BaseAd'
D, [2016-01-14T12:02:58.320401 #25646] DEBUG -- :   CategoryTag Load (4.5ms)  SELECT `category_tags`.* FROM `category_tags` INNER JOIN `category_taggables` ON `category_tags`.`id` = `category_taggables`.`category_tag_id` WHERE `category_taggables`.`category_taggable_id` = 208013 AND `category_taggables`.`category_taggable_type` = 'BaseAd'
D, [2016-01-14T12:02:58.330162 #25646] DEBUG -- :   StateTag Load (8.7ms)  SELECT `state_tags`.* FROM `state_tags` INNER JOIN `state_taggables` ON `state_tags`.`id` = `state_taggables`.`state_tag_id` WHERE `state_taggables`.`state_taggable_id` = 208013 AND `state_taggables`.`state_taggable_type` = 'BaseAd'
D, [2016-01-14T12:02:58.332070 #25646] DEBUG -- :   FriendlyId::Slug Load (0.3ms)  SELECT  `friendly_id_slugs`.* FROM `friendly_id_slugs` WHERE `friendly_id_slugs`.`sluggable_id` = 208013 AND `friendly_id_slugs`.`sluggable_type` = 'BaseAd'  ORDER BY `friendly_id_slugs`.id DESC LIMIT 1
D, [2016-01-14T12:02:58.333497 #25646] DEBUG -- :   SQL (0.3ms)  DELETE FROM `friendly_id_slugs` WHERE `friendly_id_slugs`.`sluggable_id` = 208013 AND `friendly_id_slugs`.`sluggable_type` = 'BaseAd' AND `friendly_id_slugs`.`slug` = '' AND `friendly_id_slugs`.`scope` = 'edition_id:1548,type:Ad'
D, [2016-01-14T12:02:58.337285 #25646] DEBUG -- :   SQL (1.0ms)  INSERT INTO `friendly_id_slugs` (`sluggable_id`, `sluggable_type`, `slug`, `scope`, `created_at`) VALUES (208013, 'BaseAd', '', 'edition_id:1548,type:Ad', '2016-01-14 17:02:58')
```

Note that the insert has an empty value for 'slug', and that then generates an error:

```
  Mysql2::Error: Duplicate entry 'BaseAd-edition_id:1548,type:Ad' for key=
 'index_friendly_id_slugs_on_slug_and_sluggable_type_and_scope': INSERT INTO `friendly_id_slugs` (`sluggable_id`, `sluggable_type`, `slug`, `scope`, `created_at`) VALUES (208013, 'BaseAd', '', 'edition_id:1548,type:Ad', '2016-01-14 17:02:58')
  app/controllers/ads_controller.rb:436:in `create'
```

The class in question is an STI class, and the base class includes FriendlyId:

```
extend FriendlyId
friendly_id :business_name, use: [:slugged, :history, :scoped], scope: [:type, :edition]
```

I tried adding the type of objects to the scope because I initially missed the detail that the slug was being generated as an empty string. As you can see from a few lines prior in that log, the business_name field has a value provided.

While I'm inclined to believe that it's far more likely for my code to be the issue rather than friendly_id itself, I can't figure out why it would be trying to create an empty-string friendly ID when the candidate field has a value,.

**Comment by kimrgrey** [comment]
Hi, @kbroderick. Yep, you are right, there is no any value validation for the slug model. FriendlyId is checking base column on nil value here: https://git.io/vzn5c, - but this check is allowing empty string. On the one hand it's not good idea to generate empty slug. On another hand, if empty string is acceptable as slug for base model why it should not be accepted by friendly_id?

And what about your problem. I'm not sure about it, but take a look on this documentation note about STI: https://git.io/vzn5B. May be it will helpful.

**Comment by kbroderick** [comment]
Thanks. Two thoughts:
a) at least if I'm reading the error correctly, FriendlyId is trying to create a duplicate entry in the table, which would imply a duplicate (empty-string) slug; shouldn't it still add a UUID to the conflicting slug candidate to create a unique slug?

b) the column appears to have a value (the INSERT statement shows business_name being fed 'Bill Green Jewelers DUDE'), so either the value is getting eaten somewhere between the INSERT and the slugging callback. I'm guessing this is more likely on our side, but in looking at our model, I don't see any obvious way the callbacks would be causing that.

**Comment by kimrgrey** [comment]
Yep, by some reason conflict slug was not detected  here: https://git.io/vzcIv. Can you create reproducible test snippet based on your code? Something like test [in this issue](https://github.com/norman/friendly_id/issues/717)? It would be much easier to find out what goes wrong in this case.

**Comment by kbroderick** [comment]
In trying to minimize down the test-case, I tried first removing all the callbacks in my model (without a change) and then pulling the history module out (i.e. `friendly_id :business_name, use: [:slugged, :scoped], scope: [:type, :edition]`). Removing the history module does change the behavior, however, and allows the save to work correctly (albeit at the cost of not having the history module available).

If I get a chance to, I will try to create an actual test case, but the list of critical bugs popping up at the moment means that I'm going to be putting out fires for at least few days before I can do anything else.

**Comment by kimrgrey** [comment]
Thanks, @kbroderick! Could you try to use latest friendly_id from `master` branch? Recently we've fixed few bugs connected with `history` module.

**Comment by kbroderick** [comment]
No change in behavior using 5.2.0.beta.1 (cd0c8bd87fec7a37104e44da8cb8af809357c986).
