### ISSUE TITLE
usind finders  does not work as expected with STI

### ISSUE THREAD

**Issue by lcowell** [norman/friendly_id#736]
I have the `finders` module enabled in my friendly_id initializer.

If I have a parent AR class called `Article` and subclass called `NewsPost`. I can call `NewsPost.friendly.find("sample-news-post-2")`, I can call `Article.find("sample-news-post-2")`, but when I call `NewsPost.find("sample-news-post-2")` I get the following error:

```
> NewsPost.find("sample-news-post-2")
NewsPost Load (0.3ms)  SELECT  `articles`.* FROM `articles`  WHERE `articles`.`type` IN ('NewsPost') AND `articles`.`id` = 0  ORDER BY articles.published_at DESC LIMIT 1
ActiveRecord::RecordNotFound: Couldn't find NewsPost with 'id'=sample-news-post-2 [WHERE `articles`.`type` IN ('NewsPost')]
from <removed>/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.14/lib/active_record/relation/finder_methods.rb:320:in `raise_record_not_found_exception!'
```

This behaviour was the same for friendly_id 5.0.5 and 5.1.0. I am using rails 4.1.14. I did try adding friendly_id configuration to each of the subclasses. I event was explicit about how which modules I was using. eg:

``` ruby
extend FriendlyId
friendly_id :title, use: [:slugged, :finders, :history]
```

Do you know what I'm doing wrong? Thanks in advance.

edit: this seems to work in rails 4.2. If you're not supporting rails 4.1, please feel free to close the request.

**Comment by 3den** [comment]
I am having this same problem in rails 5, in one of my models the `.find` works as expected but in 2 others it only works with `friendly.find`. The friendly_id code on all those models is exactly the same.

**Comment by yjukaku** [comment]
I'm also having this issue in Rails 5.  The model in question is namespaced (because it is in an Engine), so maybe that's where the issue lies?

**Comment by kazkovsky** [comment]
Same here, friendly_id doesn't work when using Spree models from controller of different engine

**Comment by parndt** [comment]
FriendlyId only functions when you use .friendly.find otherwise you're getting the Rails implementation which is looking at your ID column.

So if you're using the finders module then FriendlyId takes over from Rails by default.  Can anybody come up with a simple reproduction of this so that we can add tests? Or better yet a failing test that we can fix please?

**Comment by victorhazbun** [comment]
On Rails 4.2 the gem works fine. In Rails 5.1 it stops working. At least for me.

**Comment by parndt** [comment]
@victorhazbun `.friendly.find` is _always_ required.

**Comment by armchairdj** [comment]
What's the status on this issue? I'm facing it in Rails 5.2.

Steps to reproduce:

1. Implement STI
2. Use friendly_id on the parent and child models that implement STI
3. Enable finders with `config.use :finders`
4. Call `StiChildModel.find(friendly_id)`

Expected result: ActiveRecord will find the instance.

Actual result: `#find` fails with the following error:

```Couldn't find StiChildModel with 'id'=tofu_food_truck_1_i_phone_keytar_carles_quinoa_leggings_brooklyn```
