### ISSUE TITLE
Finders should differ between Strings and Numbers

### ISSUE THREAD

**Issue by svoop** [norman/friendly_id#742]
The following scenarion happens with friendly_id < 5.0 and with friendly_id >= 5.0 using the `:finders` add-on.

Given a simple User model with the standard `id` (INT) attribute as well as a `slug` (VARCHAR) used by friendly_id and a name. Say you have two Users:

```
User.create(id: 1, slug: "bruce", name: "Bruce")
User.create(id: 2, slug: '1', name: "Hulk")

User.find("bruce").name   # => "Bruce"
User.find("1").name       # => "Hulk"
User.find(1).name         # => "Hulk"    <-- OUCH!
```

This has the potential for some really nasty bugs!

My first thought: "Don't use :finders to keep things properly separated." While that's correct, as long as :finders are an official feature, it shouldn't be broken. After all, the solution is quite simple.

When overriding `find`, check the argument:
- If it's a Number instance or matches `/\A\d+\z/`, delegate it to the AR finder.
- Otherwise, proceed as you do now.

What do you think about this approach?

**Comment by khamusa** [comment]
I have a somewhat related scenario. We're using pg uuid-v4 as ids in the database, and I noticed that the following:

```ruby
some_uid = "8d575eb4-f1f4-4973-bdb7-78f45576c445"
Event.friendly.find(some_uid)
```
ends up triggering two sql statements:
```
Event Load (0.9ms)  SELECT  "events".* FROM "events" WHERE "events"."slug" = $1 LIMIT 1  [["slug", "8d575eb4-f1f4-4973-bdb7-78f45576c445"]]
  Event Load (0.8ms)  SELECT  "events".* FROM "events" WHERE "events"."id" = $1 LIMIT 1  [["id", "8d575eb4-f1f4-4973-bdb7-78f45576c445"]]
``
While locally this takes less than 1 ms, on heroku it can take quite a bit more according to the network latency we face when communicating with the DB. We ended up with something like this:

```ruby
def find_scope(base_scope, id)
  UID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/
  return base_scope if !base_scope.respond_to?(:friendly) || UID_REGEX.match?(id)
  base_scope.friendly
end
```

Which means we're basically reimplementing part of the `friendly_id` logic to prevent running that second request. We can only do this because we have the guarantee that every id we're using is of type :uuid and hence we can predict the exact string format they should match. We also count on the fact that no slug will ever satisfy that same regex (which we can assume it's true according to our domain). My point here is: since we can know upfront the :id column type on the database, there are scenarios where we may skip the slug search completely.
