### ISSUE TITLE
Rails 5 :finders compatibility

### ISSUE THREAD

**Issue by suramai** [norman/friendly_id#755]
friendly_id :name, use: [:slugged, :finders]  

 @user = User.find(params[:id])

doesn't work on Rails 5?

Things work when I use User.friendly.find(params[:id]) with friendly_id :name, use: [:slugged, :finders]  

But the documentation says  User.find(params[:id]) should work with friendly_id :name, use: [:slugged, :finders] 

I am confused. Kindly advice. Thanks

**Comment by webgago** [comment]
it seems like rails `4.2.6` has same issue

**Comment by onemanstartup** [comment]
It seems resolved in master https://github.com/norman/friendly_id/pull/728

**Comment by 3den** [comment]
can someone release a new version with this and the other fixes from master? The version on rubygems is from last year... 😞

**Comment by mattherick** [comment]
+1

**Comment by staycreativedesign** [comment]
I am still having an issue with this!

**Comment by klacointe** [comment]
:+1:

**Comment by sanjusoftware** [comment]
just updated my rails app to 5.0.0.1 and I got the same issue. Is a new version being released for this gem?

**Comment by danbernier** [comment]
Looks like v 5.2.0 was released just a few days ago, with this fix.

**Comment by ezekg** [comment]
Any update on when 5.2.0 will be officially released?

**Comment by tom-lord** [comment]
Yep, the issue was fixed in [this commit](https://github.com/norman/friendly_id/pull/728), and Rails 5 support was [added in version 5.2.0](https://github.com/norman/friendly_id/blob/master/Changelog.md#520-2016-12-01).

**Comment by prospibyte** [comment]
It looks like this is broken again as of 5.0.2 rails release. Getting ```Could not find friendly_id-5.2.0 in any of the sources. Run `bundle install` to install missing gems.```

**Comment by vishaltelangre** [comment]
Upgrading to `5.2.x` fixed this issue for us.

```diff
-gem 'friendly_id', '~> 5.1.0'
+gem 'friendly_id', '~> 5.2.0'
```

**Comment by yas4891** [comment]
I was running into this same issue with Rails `6.0.0rc1`, `cancancan (3.0.1)`, and `friendly_id (5.2.5)` again. 
Fixed it by updating friendly_id - in case someone else comes across the same error
