### ISSUE TITLE
How to use the SequentiallySlugged module?

### ISSUE THREAD

**Issue by brchristian** [norman/friendly_id#757]
I’m trying to use the old `sequentially_slugged` behavior, and noticed the [SequentiallySlugged module](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/sequentially_slugged.rb).

When I put

``` ruby
friendly_id :name, :use => :sequentially_slugged
```

into my model, just as in [sequentially_slugged_test.rb](https://github.com/norman/friendly_id/blob/master/test/sequentially_slugged_test.rb#L5), it doesn’t work and I get hit with

``` ruby
NameError: uninitialized constant FriendlyId::SequentiallySlugged
```

I’m not sure what I’m missing, and couldn’t find any documentation in the guide.

For what it’s worth, I’d like it to work within scopes, so I’m assuming I can do something like:

``` ruby
friendly_id :name, use: [:scoped, :sequentially_slugged], scope: :user
```

and use `scoped` and `sequentially_slugged` together. However I can’t even get `sequentially_slugged` working on its own right now.

Looking through the guide, I couldn’t find any documentation on how to use the SequentiallySlugged module. Am I doing something wrong? If so, what am I missing? Maybe something can be added to the guides about this for other users in a similar situation.

Thanks!

**Comment by rikkipitt** [comment]
Hi @brchristian - did you ever manage to load this module? I'm having trouble too!

Thanks,
Rikki

**Comment by brchristian** [comment]
@rikkipitt What I ended up doing was, in my `app/model/foo.rb`:

```ruby

  def slug_candidates
    [:name, :name_and_sequence]
  end

  def name_and_sequence
    slug = name.parameterize
    sequence = Foo.where("slug like ?", "#{slug}-%").count + 2
    "#{slug}-#{sequence}"
  end
```

**Comment by rikkipitt** [comment]
@brchristian thanks for taking the time to get back to me, really appreciated. I spent some time looking into the source and tried to get that module to load on init, no such luck though.

I've just tried your solution and it does the trick for my purposed, so cheers for sharing that snippet.

Rikki

**Comment by jrectenwald** [comment]
The most recent tag today is version 5.1, and the most recent commit in this version was January 15, 2015. SequentiallySlugged was added after that. SequentiallySlugged is currently in the master branch so I just specified that branch in my Gemfile.

```Ruby
gem 'friendly_id', :git => "https://github.com/norman/friendly_id.git", :branch => "master"
```
