### ISSUE TITLE
Can `find_by_slug` work with :history?

### ISSUE THREAD

**Issue by h8rry** [norman/friendly_id#759]
`Model.friendly.find("record that doesn't exist")` will raise `RecordNotFound`, but I want it to return `nil` instead.

I also need to use the History module. I tried `find_by_slug`, but it doesn't seem to work with the History module?

**Comment by parndt** [comment]
For the first request you could rescue from this exception in your code and return nil?

For the second part I'm not sure as I haven't used the history module

**Comment by rokumatsumoto** [comment]
@h8rry yes, `find_by_slug` doesn't work with History module. 
@norman i would like to hear your thoughts. 
friendly_id (5.2.5)
rails (5.2.2)

If i understand correctly, you want only slug url. (https://github.com/norman/friendly_id/issues/146)
You can redirect to root_path if you want to disallow id in the url.

``` ruby
# articles_controller.rb
def set_article
  @article = Article.friendly.find(params[:id])
end
```
``` ruby
# routes.rb
resources :articles, constraints: { id: /.*\D+.*/ } do
   resources :comments
end

# this should be last route
get '*path' => redirect('/') 
```
regex link: https://rubular.com/r/rbzX3Rqz54BxwZ 

Or you can redirect to slug url if someone wants to access with id param. 

``` ruby
# articles_controller.rb
def set_article
  @article = Article.friendly.find(params[:id])
  redirect_to action: action_name, id: @article.friendly_id, status: 301 unless @article.friendly_id == params[:id]
end
```

These workarounds work with History module.
