### ISSUE TITLE
undefined method `slug=' for Model

### ISSUE THREAD

**Issue by gs-shahid** [norman/friendly_id#765]
I am using master branch with rails 5 there is no slug field in my db as i am using another field using 
`slug_column: :column_name`

after validations it is raising `undefined method 'slug=' *` error
This error is caused by `self.slug = diff.first` from `lib/friendly_id/slugged.rb:332` in `unset_slug_if_invalid`
I changed this to `slug = diff.first` by removing `self.` and that solved the issue

**Comment by PragmaticEd** [comment]
Have same error on rails 5.*

**Comment by gs-shahid** [comment]
*Workaround:* You can set alias_attribute in your Model for this issue like 
`alias_attribute :slug, :column_name`

**Comment by edwardmp** [comment]
Same issue here on rails 5

**Comment by cgunther** [comment]
I had the same issue on Rails 4.2.7.1 starting with FriendlyId 5.2.0. #779 fixes it for me.
