### ISSUE TITLE
Please release 5.2.0.

### ISSUE THREAD

**Issue by jcoyne** [norman/friendly_id#766]
We've been waiting on a release of friendly_id in order to move our application to Rails 5.  I'd appreciate it if you cut a release soon. We've been testing against master and it works well. Thanks for all your hard work on this. It's very helpful to me.

**Comment by wenweih** [comment]
+1

**Comment by jacobhedengren** [comment]
same here!

**Comment by rhugo** [comment]
UP!

**Comment by unrau** [comment]
+1

**Comment by jacobhedengren** [comment]
+1

**Comment by oyeanuj** [comment]
@norman @kimrgrey @parndt Just wondering on what the timeline for this might be? Also, waiting on the next release like the above commenters :)

Thank you for your work on this!

**Comment by aguynamedben** [comment]
+1

**Comment by aguynamedben** [comment]
Did anybody find any temporary monkey patches that help work around this for the time being? It's also blocking our upgrade to Rails 5. The only option I can see is to change all my code to use `.find_by(slug: "blah")` everywhere.

**Comment by dalpo** [comment]
@aguynamedben The current master is working well with Rails 5.

**Comment by aguynamedben** [comment]
@dalpo Yep, that's what we ended up doing, setting a specific sha1 in our Gemfile. Good workaround until 5.2.0 is released.

**Comment by tyler-king** [comment]
Trying to update an internal Gem to Rails 5 compatible, all transitioned fine until friendly_id error. 

Through Googling and on the issues here, is the consensus to change all `.find` to `.find_by_slug`? I'm using a Gemspec file which won't let me pull from Github. Should I wait longer or move all my finds over to find_by_slug?

**Comment by parndt** [comment]
To use the FriendlyId proxy, change `.find` to `.friendly.find`

**Comment by tyler-king** [comment]
@parndt Brian fart on my part! But yes, I moved to this method, however my tests strangely still fail, not sure why, but going to investigate. Due to it being a Gemspec and not a Gemfile, I can't reference master so I'll dig into the issue further!

**Comment by parndt** [comment]
Here you go everyone: http://rubygems.org/gems/friendly_id/versions/5.2.0 :heart:
