### ISSUE TITLE
undefined method `relation' on heroku

### ISSUE THREAD

**Issue by allanjba** [norman/friendly_id#769]
App works great locally. When i push to heroku, app crashes and I get this error

`/app/vendor/bundle/ruby/2.2.0/gems/friendly_id-5.1.0/lib/friendly_id.rb:91:in`singleton class': undefined method `relation' for class`Class' (NameError)`

**Comment by AndreiMotinga** [comment]
did you run `heroku run rake db:migrate` ?

**Comment by saqib1324** [comment]
I am also receiving this same issue. How did you solve this?
