### ISSUE TITLE
ActiveAdmin: Can't save record with the same name after adding Friendly Id to existing app

### ISSUE THREAD

**Issue by StarWar** [norman/friendly_id#771]
I have no uniqueness validation for the model nor any database restriction for uniqueness for name in the table. It currently has 3000 posts. I have added friendly_id and saved each record to generate slug for the record. 

After that I am not able to save new record with same name. I'm not able to figure out issue. 

In new relic it shows following error.

`ERROR: duplicate key value violates unique constraint "index_posts_on_slug"DETAIL: Key (slug)=(bullseye) already exists.`

Here is the code in my model

``` ruby
friendly_id :slug_candidates, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    slug.blank? || slug_changed?
  end

  def slug_candidates
    [
      :slug,
      :name,
      [:name, :category]
    ]
  end
```

Here category is obtained from related record, it's not a field in same table. Error occurs when slug field is left blank. When adding unique slug it works. 

`:finders` is enabled from config file.

We use active_admin to save data.

Thanks,

**Comment by aarondmills** [comment]
I am experiencing the same issue, were you able to figure out a way to get this working?

**Comment by kashifnaseer** [comment]
Any update on this ? I'm facing same issue.
