### ISSUE TITLE
Calling super in simple_i18n

### ISSUE THREAD

**Issue by ognevsky** [norman/friendly_id#781]
Hello! 
First of all, thanks for such a great gem, saved me a lot of time!

I have an issue (or better to say a question). I can't understand why do you use [here](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/simple_i18n.rb#L94) `super`, because there is an error:

    NoMethodError: super: no superclass method `slug=' for #<Landing:0x007ff4cb24b450>
    Did you mean?  slug_de=`

So, I don't have the `slug` column in the database (I have the latest 5.2.0 version of the gem), that means that I don't have `slug=` method as well. I've created empty `slug=` method in my model, but don't think that's correct. 

As I wrote, I have the latest version of the gem, I have this in my model

    extend FriendlyId
    friendly_id :title, use: [:slugged, :simple_i18n]

Also I have columns `slug_en`, `slug_cs`, `slug_de` and `slug_pl` in my model. 

Thanks for any help, 
Andrey.

**Comment by hugoarpin** [comment]
Same issue here #772.
