### ISSUE TITLE
NoMethodError: undefined method `slug_column=' for #<#<Class:0x007f8355b0a3d0>:0x007f8355b0a330>

### ISSUE THREAD

**Issue by vfonic** [norman/friendly_id#786]
The config option `slug_column` doesn't seem to work on latest rails 4.x (4.2.7.1)
The same option works when passed directly in the model:
```rb
  friendly_id :title, use: [:finders, :slugged], slug_column: :handle
```

I've created a repo that shows the bug:
https://github.com/vfonic/unfriendlyid

Repro steps:
```sh
$ rails new unfriendlyid
$ cd unfriendlyid
$ echo "gem 'friendly_id'" >> Gemfile
$ bundle install
$ rails g scaffold Page title handle:index
$ rails g friendly_id
$ rails db:create db:migrate
$ open config/initializers/friendly_id.rb
```

Uncomment slug_column line and change `slug` to `handle`:
```rb
  config.slug_column = 'handle'
```

```sh
$ open app/models/page.rb
```

Make `Page` model look like this:

```rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end
```

Try it out in the console:
```sh
$ rails c
$ Page.create title: 'Asd DSA'
```

**Comment by kwent** [comment]
Same here !

**Comment by parndt** [comment]
@vfonic sorry for the non-response, we were buried under a lot of stale issues but it's now much easier to see things. Keen to know if this is still an issue?

**Comment by vfonic** [comment]
I just updated the repro steps above.

This is still an issue and I figured out when it happens and when it doesn't:

The `config/initializers/friendly_id.rb` call to `config.slug_column=` requires `config.use :slugged` to be uncommented.

So this won't work:

```rb
# app/models/page.rb

class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end
```
```rb
# config/initializers/friendly_id.rb

# ...
  # ## Slugs
  #
  # Most applications will use the :slugged module everywhere. If you wish
  # to do so, uncomment the following line.
  #
  # config.use :slugged
  #
  # By default, FriendlyId's :slugged addon expects the slug column to be named
  # 'slug', but you can change it if you wish.
  #
  config.slug_column = 'handle'

# ...
```

Whereas this works:


```rb
# app/models/page.rb

class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title#, use: :slugged
end
```
```rb
# config/initializers/friendly_id.rb

# ...
  # ## Slugs
  #
  # Most applications will use the :slugged module everywhere. If you wish
  # to do so, uncomment the following line.
  #
  config.use :slugged
  #
  # By default, FriendlyId's :slugged addon expects the slug column to be named
  # 'slug', but you can change it if you wish.
  #
  config.slug_column = 'handle'

# ...
```

**Comment by parndt** [comment]
Ah so it overrides the global config when you specify it per model?

**Comment by vfonic** [comment]
Hmm I don't understand what you mean. Basically it works when both `config.use :slugged` and `config.slug_column = 'handle'` are set in global config.

It doesn't work when `config.use :slugged` is NOT set in global config, but it is set in the model.

In other words, global setting `config.slug_column = 'handle'` is ignored when `config.use :slugged` is commented out in the global settings.

**Comment by parndt** [comment]
Thanks 😄
