### ISSUE TITLE
Prevent looking up users by Id

### ISSUE THREAD

**Issue by ACPK** [norman/friendly_id#790]
How would you prevent users from looking up users by id? For example, you can type /users/100 to see if the site has a user with an id of 100.

**Comment by ezekg** [comment]
Hey, @ACPK I know it's late but you could use,

```ruby
User.find_by_friendly_id id
```

instead of the regular finder method that falls back to the ID query.

**Comment by vladi160** [comment]
I am getting error

> undefined method `find_by_friendly_id'  Did you mean? find_by_sql
