### ISSUE TITLE
"basico" error route, 404

### ISSUE THREAD

**Issue by laerciocrestani** [norman/friendly_id#794]
Hello, I am using version 5.1.0 of GEM, and the error is when I use a title with the word 'basic' in the slug.

Only when updating the registry ..
![captura de tela 2017-02-20 as 09 27 15](https://cloud.githubusercontent.com/assets/1430869/23125074/d1f3bb0a-f74e-11e6-9d17-a166bdc15207.png)

If you change the slug to "...-basica", for example it works perfectly.

Follow my Model.

extend FriendlyId
friendly_id :nome, use: [:slugged, :finders]

**Comment by hajder** [comment]
This question should be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/friendly-id), not here.
