### ISSUE TITLE
Deprecation Warning Rails 5 - attribute_change

### ISSUE THREAD

**Issue by kasiabernad** [norman/friendly_id#804]
I receive This Deprecation Warning related with your code.
```
DEPRECATION WARNING: The behavior of `attribute_change` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute` instead.
```

**Comment by lazyatom** [comment]
You may be interested in [this discussion](https://github.com/norman/friendly_id/pull/816#issuecomment-316346095) on #816

**Comment by kyletolle** [comment]
I came across this issue and others in this repo (#816, #862, #867) while investigating how to handle Rails deprecations in relation to FriendlyId slugging. I'm not currently very familiar with FriendlyId or how it's used in our models.

I notice that in our model's `#should_generate_new_friendly_id`, we use a `*_changed?` method. My question was then whether FriendlyId called this method before saving or after saving the record. This would determine whether we needed to use a `#saved_change_to_*?` or `#will_save_change_to_*?` type check. After some digging, I found that `#should_generate_new_friendly_id` is called in [`#set_slug`](https://github.com/norman/friendly_id/blob/9cd4ce2b5d0425aa704872e1334b442cab03c29c/lib/friendly_id/slugged.rb#L356). And `#set_slug` is run as a [`before_validation`](https://github.com/norman/friendly_id/blob/9cd4ce2b5d0425aa704872e1334b442cab03c29c/lib/friendly_id/slugged.rb#L250). This means that our use of `*_changed?` should instead be `will_save_change_to_*?`

I hope this helps some other people in the future.

**Comment by lazyatom** [comment]
@kyletolle which version of Rails are you running against?

**Comment by kyletolle** [comment]
@lazyatom We are in the process of upgrading to Rails 5.2.3.
