### ISSUE TITLE
Error: Directly inheriting from ActiveRecord::Migration is not supported.

### ISSUE THREAD

**Issue by craiglinton** [norman/friendly_id#805]
After installing the gem, I encountered the following error when attempting to run `rails db:migrate`:

> rails aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
> 
>   class CreateFriendlyIdSlugs < ActiveRecord::Migration[4.2]

The way to fix the error was to put `[5.1]` at the end of `ActiveRecord::Migration`.

**Comment by aCandidMind** [comment]
Duplicate of #797
