### ISSUE TITLE
Using id and slug both

### ISSUE THREAD

**Issue by alagu** [norman/friendly_id#806]
Hey @norman,

Thanks a lot for the library. It is super useful. What I wanted to know is that if we could use the friendly id along with original id. ie. I want to use /question/:id/edit but /question/:slug for show

Is it possible?

Thanks!

**Comment by hajder** [comment]
This can be done but would require you to pass the slug every time you generate `question_path` and id every time you generate `edit_question_path`, etc. Unless there is a very good reason to do that it will unnecessarily complicate your code.

This question should be asked on [StackOverflow](http://stackoverflow.com/questions/tagged/friendly-id), not here.
