### ISSUE TITLE
Slug plus username

### ISSUE THREAD

**Issue by ddonche** [norman/friendly_id#808]
I am wondering if it's possible to automatically include the username in the slug to help make it more unique. For example, instead of a blog post being
`/blogs/how-to-lose-weight`

It might be
`/blogs/ddonche-how-to-lose-weight`

This way it will allow someone else to post a blog called how to lose weight without worrying about it.

**Comment by hajder** [comment]
Yes, that's what `slug_candidates` are for. You could do this for example:

```
  friendly_id :slug_candidates, use: :slugged

  deletage :name, to: :user, prefix: true

  def slug_candidates
    [
      [user_name, :name]
    ]
  end
```

**Comment by ddonche** [comment]
Man, this is exactly what I was looking for. It didn't even occur to me to use slug candidates at all to accomplish this. Thank you.
