### ISSUE TITLE
Using friendly_id with commentable

### ISSUE THREAD

**Issue by ddonche** [norman/friendly_id#810]
I have the friendly_id gem installed and it works great. My issue is I have comments that have polymorphic relations to several other things, like blogs. I set up the comments to be found by the id of both, for example blog id, then comment id. Like so in my comments controller:
```
  def load_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end
```
My problem is now that I have friendly ids for everything, this is no longer working. It's pulling the friendly id, of course.

`Couldn't find Blog with 'id'=cobra-kai-here-we-go-again`

How can I fix this so it finds the resource the comment belongs to by the friendly id?

**Comment by ddonche** [comment]
Fixed this by changing it to 
`resource.singularize.classify.constantize.friendly.find(id)`

**Comment by MswordArt** [comment]
> resource.singularize.classify.constantize.friendly.find(id)

It solved my issue too...
thanks!
