### ISSUE TITLE
undefined method `username' for nil:NilClass

### ISSUE THREAD

**Issue by ddonche** [norman/friendly_id#818]
I have a model, Goal, which uses friendly_id. I have it set up to add the username to the slug, and all was working great until I added a has_many_through association so users could participate in the Goals. 
I'm getting a `undefined method 'username' for nil:NilClass` error whenever I try to add a new goal now:
```
  def slug_candidates
    [
      [user.username, :title]
    ]
  end
```
This is my model, goal.rb:
```
class Goal < ApplicationRecord
  
  belongs_to :user
  has_many :participations
  has_many :users, through: :participations
  
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  delegate :username, to: :user, prefix: true
  
  def slug_candidates
    [
      [user.username, :title]
    ]
  end
  
  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
...
```
user.rb
```
class User < ApplicationRecord      
  extend FriendlyId
  friendly_id :username, use: :slugged
         
  validates :username, presence: true, length: { minimum: 4, maximum: 16 } 
  validates_uniqueness_of :username

  has_many :goals, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :goals, through: :participations, source: :goal
```
The controller (Goal#create) that it says is giving me trouble.
```
  def create
    @goal = current_user.goals.build(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'New goal saved successfully!' }
      else
        format.html { render :new }
      end
    end
  end
```
I get the feeling it has to do with the new association, but I can't figure out how to fix it. If I remove the 
```
  has_many :participations, dependent: :destroy
  has_many :goals, through: :participations, source: :goal
```
from the user.rb model, it moves on to other error messages, so that is where I believe the trouble is.

**Comment by parndt** [comment]
Did you ever solve this? I'm closing because it's stale, and my impression is that it's something we can't easily support. Thanks!
