### ISSUE TITLE
Make the README.md file readable again

### ISSUE THREAD

**Issue by zedtux** [norman/friendly_id#820]
The `README.md` file is a mess now.

It's no more easy to understand how to use this gem.

Remove the updates from versions 5.x, use a `CHANGELOG.md` file for that, and put a real working example working by coping/pasting.

**Comment by parndt** [comment]
Thanks for your feedback @zedtux - it seems like the most straight forward way to discuss your recommendations would be if you would care to open a pull request with these changes. Are you willing to help us in this way please?

**Comment by zedtux** [comment]
Thank you @parndt for the pings, I finally took the time to do it.
