### ISSUE TITLE
"Sluggable must exist" when using history on a paranoid model

### ISSUE THREAD

**Issue by joostvanrijn** [norman/friendly_id#822]
I have a Category model with friendly id and acts_as_paranoid.
When I create a new category, but want it to be hidden at first I set the deleted_at column, but then Slug can't find the appropriate record, since it uses the `deleted_at IS NULL` scope.

If I extend slug.rb with the code in the pr #821 it works just fine. Should this not be the default behaviour?

**Comment by jnylen** [comment]
Same here.

I'll check if your PR works.

**Comment by padi** [comment]
@joostvanrijn can you verify that the test in #838 is the setup you have? If so, then that pull request should fix your problem.
