### ISSUE TITLE
Friendly ID can break configuration via initializers

### ISSUE THREAD

**Issue by lazyatom** [norman/friendly_id#823]
When upgrading to Rails 5.0, the `rails app:upgrade` command will generate `config/initializers/new_framework_defaults.rb`, which contains the following lines:

```ruby
# Require `belongs_to` associations by default. Previous versions had false.
Rails.application.config.active_record.belongs_to_required_by_default = true
```

If Friendly ID is present, this setting will not actually have any effect in the app; this can be verified in the console:

```ruby
ActiveRecord::Base.belongs_to_required_by_default => nil
```

I have replicated it in a brand new Rails 5.1 app.

In a nutshell, because Friend ID references `ActiveRecord::Base` while it is loading (see [object_utils.rb](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/object_utils.rb#L69)), it triggers the `on_load` event (see [active_record/railtie.rb](https://github.com/rails/rails/blob/v5.1.2/activerecord/lib/active_record/railtie.rb#L110) in Rails itself), which transmutes all the existing config settings into `ActiveRecord::Base`. 

Rails will only call the `on_load` event once, and because it happens before any initializers have been read, this means that any configuration of ActiveRecord in an initializer that takes place via the `Rails.application.config.active_record` object is essentially ignored when Friendly ID is present. This impacts Rails 5.0 and Rails 5.1 at the moment.

### Possible solutions

I can think of two basic ways to work around this:

#### Defer loading Friendly ID

First, change `Gemfile` to include `gem 'friendly_id', require: false`. Then, add to `config/initializers/friendly_id`:

```ruby
initialize do
  require 'friendly_id'
end
```

#### Defer loading ActiveRecord

First move the `include` call and references to `ActiveRecord::Base` into a method, something like `FriendlyID.setup`:

```ruby
module FriendlyId
  def self.setup
    [
      ActiveRecord::Base,
      Array,
      FalseClass,
      Hash,
      NilClass,
      Numeric,
      Symbol,
      TrueClass
    ].each { |klass| klass.send(:include, FriendlyId::UnfriendlyUtils) }
  end
end
```

That's just a rough sketch, but the key is that there are no references to the `ActiveRecord` constant that get hit merely by requiring these files. Then, either add a call `FriendlyID.setup` in an `initializer` block as above, or add a `Railtie` for FriendlyID:

```ruby
module FriendlyId
  class Railtie < Rails::Railtie
    initializer "friendly_id.setup" do
      ActiveSupport.on_load(:active_record) do
        FriendlyId.setup
      end
    end
  end
end

# in lib/friendly_id.rb:
require 'friendly_id/railtie' if defined?(Rails)
```

I'd be very happy to work up a pull request for either approach; in the short term I'll be using the first one in our own app as a workaround.

**Comment by thomasdarde** [comment]
Hello Everyone ?
Any reply on this important issue ?

**Comment by thomasdarde** [comment]
@lazyatom Did you resolve this issue, I think the PR will be accepted if created :)

**Comment by lazyatom** [comment]
I'd like to get buy-in to a particular approach from one of the maintainers before I work on a pull request, as at least one the options is quite a significant change to how Friendly ID loads...

**Comment by thomasdarde** [comment]
I perfectly undersand

@parndt  do you have a thought on this ?

**Comment by parndt** [comment]
I think the railtie approach is the best!

**Comment by lazyatom** [comment]
Pull request submitted: #852
