### ISSUE TITLE
Rails 5.1 app finders not working where Model.friendly.find works

### ISSUE THREAD

**Issue by noctivityinc** [norman/friendly_id#827]
We just upgrade to Rails 5.1 from a Rails 4.2, which was a Rails 3.2 app that uses Friendly ID.

In `congif/friendly_id.rb` we have `config.use :finders` and in our Products model we have the following:

```
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
```

So we should be able to use `Product.find(params[:id])` to find a record.  Unfortunately, this is returning nil where `Product.friendly.find(params[:id])` works fine.

We also tested it with `Product.find(Product.first.to_param)` and `Product.friendly.find(Product.first.to_param)` with the same result.

I am sure you will need more information to debug this, so please let me know what else we can provide.

**Comment by RigoTheCEO** [comment]
Same here +1

**Comment by isuru** [comment]
https://stackoverflow.com/questions/37671409/how-to-get-friendly-id-gem-get-working-with-rails-5-0-0-rc1#45215275

**Comment by noctivityinc** [comment]
Thanks.  That should do it.
