### ISSUE TITLE
Regenerating slug when same as reserved words

### ISSUE THREAD

**Issue by oyeanuj** [norman/friendly_id#830]
Hi @parndt, thank you for supporting this library! Not sure if this question is a bug or a feature request but would really appreciate your thoughts.

**TLDR;** *How does one deal with (ideally, globally) regenerating slugs or providing slug candidates when the initial slug choice may conflict with a reserved word?*

---
**Detailed version**
In my app, there are cases when I get this message:
```sh
ActiveRecord::RecordInvalid: Validation failed: Friendly is reserved
```

Model:
```rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id 	:slug_candidates,
	use: 		[:slugged, :history]
  
  # ... more model code ...
  
  def slug_candidates
    [:name]
  end
end
```

Now, based on the documentation:
> Now that candidates have been added, FriendlyId no longer uses a numeric sequence to differentiate conflicting slug, but rather a UUID (e.g. something like 2bc08962-b3dd-4f29-b2e6-244710c86106). This makes the codebase simpler and more reliable when running concurrently, at the expense of uglier ids being generated when there are conflicts.

..I'd expect to see a UUID when the candidates conflict with the reserved words. So, is the error being thrown a bug or expected behavior?

And in either case, what is (an ideally global) workaround that you'd recommend?

Thank you!

**Comment by oehlschl** [comment]
I was actually just about to report the same behavior, since I agree with the idea of reserved words but think it's sufficient if 'admin-UUID' were used instead of raising an exception.

**Comment by oehlschl** [comment]
It's noting that in the changes as implemented, available slug candidates are still preferred over reserved words.

Reserved words are filtered out of the candidate pool unless ALL of the candidates are reserved; only if all candidates are reserved will the UDID be added to the first. I think this matches the logic for non-reserved words, and it still handles the default case more gracefully than raising an exception.

**Comment by parndt** [comment]
@oyeanuj can you try with the latest master branch?

**Comment by oyeanuj** [comment]
@parndt Just tested, and it works! 

@oehlschl Thank you for the quick PR! Do you think this should be a global configuration in the initializer rather than folks having to do it in each model?

**Comment by oyeanuj** [comment]
Also TLDR in case anyone else stumbles upon this ticket: the solution is to use `	treat_reserved_as_conflict: true` where you setup `friendly_id` in your model.

**Comment by oehlschl** [comment]
@oyeanuj you can configure this globally in an initializer as described (briefly) in the readme. In our initializer, we have `config.treat_reserved_as_conflict = true` right below: https://github.com/norman/friendly_id/blob/master/lib/friendly_id/initializer.rb#L19

I didn't invest time in updating the docs in this PR since I wasn't sure if it was likely to be merged, but that would help clarity things as well.

**Comment by oehlschl** [comment]
I'll leave it to the gem maintainers do to device whether this should be default behavior in the future as well. I made it opt-in to avoid unexpected regressions for other users.

**Comment by parndt** [comment]
Making it opt-in means we can push a normal gem release for it now. If it becomes really popular we can always make it default.

Thanks again!
