### ISSUE TITLE
When there are same slugs.

### ISSUE THREAD

**Issue by vladi160** [norman/friendly_id#833]
Hi, when user is created, it creates slug for it based on the username column. For the example the slug can be 'sara', but after that when new user is registered with same username, the generated slug is something like that: `sara-11e0bc89-1f43-4e41-a0f8-8cc2d8d9c4a9`.
Is there way next slug for same username to be something like username-count, where count is a count of all same usernames + 1.
Or is there another way, just slug to be more simple ?

**Comment by jrectenwald** [comment]
Hey,

What you described is actually the way friendly_id used to work. They've moved that behavior into a module called sequentially_slugged. 

Take a look at this [issue](https://github.com/norman/friendly_id/issues/757)
