### ISSUE TITLE
Unique Slugs by Scope not working

### ISSUE THREAD

**Issue by pranav7** [norman/friendly_id#840]
Even after using `:scope`, friendly_id is generating a hashed version of the slug.

`friendly_id (5.1.0)`
`rails (5.1.4)`
`ruby (2.1.4`

```ruby
class Board < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:scoped, :slugged, :history], scope: :company

  belongs_to :company
  has_many :posts

  validates :slug, presence: true, uniqueness: { scope: :company }
end
```

```terminal
> Board.create name: "Test Board", company: company
=> #<Board:0x007f8e192b53f0
 id: 19,
 company_id: 19,
 name: "Test Board",
 description: nil,
 created_at: Fri, 06 Oct 2017 09:06:26 UTC +00:00,
 updated_at: Fri, 06 Oct 2017 09:06:26 UTC +00:00,
 slug: "test-board">

> Board.create name: "Test Board", company: company
=> #<Board:0x007f8e1bb4e820
 id: 20,
 company_id: 19,
 name: "Test Board",
 description: nil,
 created_at: Fri, 06 Oct 2017 09:06:40 UTC +00:00,
 updated_at: Fri, 06 Oct 2017 09:06:40 UTC +00:00,
 slug: "test-board-1781b893-4c25-4875-acf4-0fb23ca09c52">
```

Am I missing something? I referred to: http://norman.github.io/friendly_id/file.Guide.html#Unique_Slugs_by_Scope

**Comment by parndt** [comment]
In your example you're creating both `Board` records for the same `company` (id `19`). In this case we'd expect that there would be a conflict which would get resolved by appending the UUID. 

Is this the problem?

**Comment by pranav7** [comment]
>  In this case we'd expect that there would be a conflict which would get resolved by appending the UUID.

Yes. I was expecting that this would throw a validation error? Am I missing a configuration? Or is this the expected behavior?

**Comment by pablougas** [comment]
Is there a way to throw in validation errors? I'm in the sam eboat as @pranav7, Ideally, I can go through a series of scoped: [:city, :company, :id] and then also make the slugs changeable via the user like the facebook url generator

**Comment by pablougas** [comment]
found some info on slack

`friendly_id :name, use: [:slug_candidates, :slugged, :history]`

`def slug_candidates
    [
      :name,
      [:name, :city],
      [:name, :city, :company],
    ]
  end
`

**Comment by parndt** [comment]
Yes, you can use slug candidates for this second case. 😄 

Appending a UUID is the expected behaviour. If you want to throw a validation error on a duplicate `Board#name` then you can use standard Rails uniqueness validations for this outside of FriendlyId, or even better put a unique constraint on the column and your database will take care of it.

It sounds as if FriendlyId is working as expected, so I'm going to close this issue.

Thanks all!
