### ISSUE TITLE
Could not find generator 'friendly_id'

### ISSUE THREAD

**Issue by jacob-hedengren** [norman/friendly_id#841]
Hi,

Today all of a sudden I have some issues installing the gem. I am running rails 5.1.4 and ruby 2.4.2. I tried some different versions of the gem but I am getting the "Could not find generator 'friendly_id'. Maybe you meant 'helper', 'channel' or 'mailer'. Run `rails generate --help` for more options." error when running "rails generate friendly_id". I have confirmed the gem is installed when running bundle install. Anyone know what the problem could be? I have installed it a 100 times before without any problems. 

Thanks in advance!

**Comment by parndt** [comment]
Did you find any solution @jacob-hedengren ?

**Comment by luicode** [comment]
Getting the same error too - any update on this?

**Comment by jacob-hedengren** [comment]
Hi everyone, seems like sometimes this problem occurs and sometimes not. I am running Rails 5.1.5.rc1 and Ruby 2.5.0. I am using gem 'friendly_id', '~> 5.1.0' in my gemfile. Any workaround?

**Comment by parndt** [comment]
Are you able to make an example project available that reproduces this with minimal changes please?

Also does it work with Rails 5.1.4?

**Comment by jaywad** [comment]
Hi everyone, I am using Rails 5.2.0 and getting the same error ```Could not find generator 'friendly_id'```. I tried using both gem versions (5.1.0 and 5.2.4) but nothing worked.

Any update on this - much appreciated?

**Comment by parndt** [comment]
What command are you running? `bundle exec rails generate friendly_id`? Can you please show your `Gemfile` & `Gemfile.lock`?

**Comment by jaywad** [comment]
@parndt Thanks for your reply. Finally it worked for me after executing `spring stop` 😄
I was running both commands `bundle exec rails generate friendly_id` and `rails generate friendly_id` and was getting same result.

**Comment by parndt** [comment]
Ah, good old `spring stop`..........

**Comment by therealrodk** [comment]
Rails 6.0.2 app. `spring stop` did the trick.

**Comment by yunggindigo** [comment]
thank you `spring stop`

**Comment by tingtinghsu** [comment]
> I had the same issue (Rails 5.2.2), so I added `gem 'friendly_id', git: 'https://github.com/norman/friendly_id'` in my gemfile and seemed to have fixed my issue.

Thanks! It works for me.
