### ISSUE TITLE
undefined method `find_by_friendly_id'

### ISSUE THREAD

**Issue by vladi160** [norman/friendly_id#846]
I am using it because I want to prevent selecting user from his id, but I am getting this error:

> undefined method `find_by_friendly_id' for #<Class:0x00000008ae99f0> Did you mean? find_by_sql

This is the model:

`    include FriendlyId
    friendly_id :name, :use => [:slugged, :finders]`

and the controller:

`@user = User.find_by_friendly_id(params[:slug])`

**Comment by parndt** [comment]
Please see our [usage section of the readme](https://github.com/norman/friendly_id#usage):

```ruby
extend FriendlyId
friendly_id :name, use: [:slugged, :finders]
```

Does that work better?

**Comment by vladi160** [comment]
`@user = User.friendly.find(params[:slug])` works fine, but `find_by_friendly_id` doesn't and I want to use it, because I don't want a result, if it is id provided, instead slug. For now, I am using dynamic method from Rails - `find_by_slug`

**Comment by parndt** [comment]
Ah - `find_by_slug` is the correct finder to use in this regard 😄
