### ISSUE TITLE
Work around on translations and update not returning with new slug.

### ISSUE THREAD

**Issue by acprsadmin** [norman/friendly_id#848]
Got a site with Eng French and Arabic. The globalize friendly id gem i tried but the arabic slugging is not going to be workable (a slug fest). So what I have done is just use Friendly ID and placed the slug in the Object table rather than the Object.translations. This means that all slugs will be in english which is fine...once on english page they can switch languages. 
However the object names are in the Translation table. So to make this work I have to create a "slug_name" column in the main object table. This stores the english object name from the Translation table. If an update is made it will store the new slug_name after editing using simple ruby code inside the create and update methods. So far so good. 

But after updating the page will want to return to the original slug and not the newly edited slug. Thus an error. Any workaround here.? Something like "redirect_to object/newslug" ???
Thanks

Also... if you edit the name field it won't save the new slug unless you make the slug nil. It won't overwrite the slug if there is a value in the slug field.

**Comment by parndt** [comment]
could you use `redirect_to object.reload` or similar?
