### ISSUE TITLE
Does not work if included in abstract base class (Stack level too deep; Tested in Rails 5.1)

### ISSUE THREAD

**Issue by wmakley** [norman/friendly_id#851]
Ruby 2.4.2; Rails 5.1.4; FriendlyID 5.2.3

Steps to reproduce:

1. Create a new Rails project and add the 'friendly_id' gem.

2. Add to ApplicationRecord:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include FriendlyId
end
```

3. Create a new model, I made a Product model with a "name" column:

```ruby
class Product < ApplicationRecord
  # include FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true
end
```

4. Test save fails:

```ruby
test "it saves" do
  product = Product.new(name: 'test')
  assert product.save!
end
```

In my own investigations, I found that the friendly_id_config method calls itself infinitely, because @friendly_id_config is initially nil (it is reading it from the wrong class).

**Comment by cernyjakub** [comment]
I experienced the exact same behavior.

**Comment by wmakley** [comment]
I tried multiple fixes, but I ultimately had to admit that I did not understand the "friendly_id_config" method at all, and the ActiveSupport methods it is using. I implement my own configurable macro modules in a more simple way.

**Comment by mikesutton** [comment]
I had this too and spent a bit of time experiment down the abstract route. Here is what worked. A bit better I think:

1. Create a concern/module

```
module Sluggable extend ActiveSupport::Concern

  included do
    include FriendlyId
    friendly_id :slug_name, {:use => [:slugged, :finders]}
  end


  private
  def slug_name
    [:name, [:name, :slug_id]]
  end

  def slug_id
    self.class.where('lower(name) = lower(?)', self.name).count
  end

  def should_generate_new_friendly_id?
    self.slug.blank? || self.name_changed?
  end
end

```

2. Include that in the class that you want to have a slug (you will need to have created a slug column on this model.
```
class <SluggedModel> < ApplicationRecord
  include Sluggable
```

**Comment by hs-dliaska** [comment]
doesn't work in rails 7 either
