### ISSUE TITLE
Allow to config conflict resolving startegy

### ISSUE THREAD

**Issue by ramigluzman** [norman/friendly_id#854]
Currently conflicts for slugs are resolved by `SecureRandom.uuid` though in some cases it is redundant to add 36 additional chars (it's even an overkill when indexing this column in SQL databases!). In my case, 4-6 chars are definitely enough (using `SecureRandom.hex(3)` for example).

https://github.com/norman/friendly_id/blob/master/lib/friendly_id/slugged.rb#L321

Make sense?
Thanks! 😃

**Comment by parndt** [comment]
Makes sense.. you could override the method per model:
```
  def resolve_friendly_id_conflict(candidates)
      uuid = SecureRandom.hex(3)
      [
        apply_slug_limit(candidates.first, uuid),
        uuid
      ].compact.join(friendly_id_config.sequence_separator)
    end
```

**Comment by ramigluzman** [comment]
@parndt I ended defining `slug_candidates` instead.
```Ruby
def slug_candidates
  [
    :title,
    [:title, ->{ rand 1000 }]
  ]
end

**Comment by parndt** [comment]
Ah - even better!
