### ISSUE TITLE
NoMethodError: undefined method `slug' for <#Table...>

### ISSUE THREAD

**Issue by giacomo-giovenzana** [norman/friendly_id#855]
I am using rails 5.1.1, I have an already existing app (with tables, controllers, views, db data and so on) and I have added the gem by Gemfile.
I have followed line-by-line all steps from the documentation page https://github.com/norman/friendly_id, but when I run:
`Table.find_each(&:save)`
I got the following error:
`NoMethodError: undefined method `slug' for <#Table...>`
For solving this issue I had to add the columns slug into my db schema and then run a migration.
So, I had to:

1. Adding a new migration
`$ rails g migration AddSlugToTable`
2. In the migration file, adding:
`class AddSlugToTable < ActiveRecord::Migration[5.1]
  def change
    add_column :tables, :slug, :string
    add_index :tables, :slug, unique: true 
  end
end`
3. Executing db migration
`$ rails db:migrate`
4. From rails console, executing the entry saving:
`> Table.find_each(&:save)`

I don't know if this is a well-known behavior, if I miss something (so that it could be also my mistake) or it is a bug/documentation hole.
I have opened this ticket just for sharing my experience, hoping it could be useful.

**Comment by raduciobanu22** [comment]
Got the same issue here.

**Comment by woniesong92** [comment]
+1

**Comment by raduciobanu22** [comment]
There's an example here http://norman.github.io/friendly_id/file.Guide.html, "Slugged Models" section where it shows you need to write a migration that adds the slug field to your table.

**Comment by gilcierweb** [comment]
Soluction
```ruby
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name #without a migration that adds the slug field to your table
end

#with migration
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged #with a migration that adds the slug field to your table
end
```
