### ISSUE TITLE
Deprecation warnings when using Rails 5.2.0.rc1

### ISSUE THREAD

**Issue by pranav7** [norman/friendly_id#856]
After upgrading Rails to `5.2.0.*` I have been getting this deprecation warning while running tests.

> DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"friendly_id_slugs\".id DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql()

Here is the [ActiveRecord changelog](https://github.com/rails/rails/blob/5-2-stable/activerecord/CHANGELOG.md#rails-520beta1-november-27-2017) that requires raw SQL fragments to be explicitly marked.

I am running `friendly_id (5.2.3)` with `rails 5.2.0.rc1`

Thanks for all the work on this gem, it's super useful! 👍

**Comment by joelmoss** [comment]
Already fixed in a29e7d7cc280d7d46c181f58fabd7cc9be67eefe 👍

**Comment by jharinek** [comment]
@norman is there a timeline for next release where this will be included? I'd be happy to help with it if needed. Thanks!

**Comment by swrobel** [comment]
Rails 5.2 final is out!

**Comment by mmoll** [comment]
Could we have a new release with this, please? :pray:

**Comment by valscion** [comment]
Version 5.2.4 contains a fix for this, so this issue can be closed.

**Comment by hernanvicente** [comment]
I can confirm that updating
From: friendly_id (5.1.0)
To:   friendly_id (5.2.4)
On Rails 5.2.1 solves the warning, thanks!

**Comment by parndt** [comment]
Thanks all 😄
