### ISSUE TITLE
Working With Slugs

### ISSUE THREAD

**Issue by therealrodk** [norman/friendly_id#861]
In the guide, under Working With Slugs > Column or Method?, it says:

"Here's an example of a class that uses a custom method to generate the slug:

```
class Person < ActiveRecord::Base
  friendly_id :name_and_location
  def name_and_location
    "#{name} from #{location}"
  end
end
```

But I was only able to get it working after making the following alterations to the code:

```
class Verse < ApplicationRecord
  extend FriendlyId
  friendly_id :passage_reference, use: :slugged
  
  def passage_reference
    "#{ book } #{ chapter } #{ number }".parameterize
  end
end
```

Specifically, the Guide does not say to `extend FriendlyId` or `use: :slugged`, which were both required in order for this to function. Also, the slugs that were generated did not get separated by dashes; instead, they were escaped with things like %20. So, I had to call parameterize on the string explicitly. In the end, I got it to work, but this may affect other users.

**Comment by parndt** [comment]
Thank you! Can you please link to the guide? I can only find one in the slugged module which has [the correct documentation](https://github.com/norman/friendly_id/blob/877c096d2eee2aad048e457d7712dce499cebb0d/lib/friendly_id/slugged.rb#L77-L96).

**Comment by therealrodk** [comment]
Wow, my friend. It has been so long now that I have no idea where I was looking. I'm happy to see that the docs are correct, and sorry to waste your time!
