### ISSUE TITLE
 undefined method `slug=' for

### ISSUE THREAD

**Issue by VivekDabhi** [norman/friendly_id#864]
i have create a new user model and add slugger on these model but issue generate
 undefined method `slug=' for

please give me solution
how to solve these problem

**Comment by parndt** [comment]
If possible, please give us more code so that we can see what you mean 😄

**Comment by capdiz** [comment]
I think what he means is that, on first time installation, when you have existing records and you run `User.find_each(&:save)` the `slug` column isn't added to User table the first time you run `rails generate friendly_id` migration.

You therefore get 

> undefined method slug for Class name

What i did was generate a migration and added the column [slug] manually to Class table.

**Comment by Uysim** [comment]
I faced this problem too

**Comment by Uysim** [comment]
@capdiz  if we need to add column slug. So what table friendly_id_slugs use for?

**Comment by VivekDabhi** [comment]
Hello,
please refer these URL

https://hackernoon.com/using-custom-slugs-for-rails-urls-500eb3f58f3c?gi=bd87a2b3187d

Thanks & Regards,
VIVEK H. DABHI

*Mobile: +91 960 108 9404*
*https://www.facebook.com/vivek.dabhi.125
<https://www.facebook.com/vivek.dabhi.125>*
*"**Don't ask God to make your Problem Easier!Trying Yourself*"

**Comment by parndt** [comment]
Fixed by #889
