### ISSUE TITLE
Handling white space at the end of the attribute 

### ISSUE THREAD

**Issue by EGrozdev** [norman/friendly_id#866]
First of all, thank you very much for the very nice script. As long as you understand all details it works amazing! Thank you, Norman, for this!

Small issue I faced is - I noticed that two different users with name = "Alice" and name = "Alice " has the same slug = "alice" which creates wrong link for the second user.
I handled this issue by squishing the name before validate, but I would suggest to have more solid solution for such cases. Like slug = "alice_" for the second user.
Regards,
Evgeny

**Comment by parndt** [comment]
Thanks for the feedback! 

I think that handling cases like that is outside the scope of what we're trying to do with FriendlyId as from my perspective the second name `Alice ` is invalid input which as you say is handled by trimming the whitespace before validation.
