### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by chrisnopa** [norman/friendly_id#869]
Hey everyone,
First, I tried to solve this error on my own, but despite all my efforts, I'm still not sure of what fails exactly when I try to run `db:migrate`! I keep getting this error message:
```rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFriendlyIdSlugs < ActiveRecord::Migration[4.2]```   
I am using Rails 5.2 version and i checked my gemfile, here is what I find:
```
gem 'friendly_id', '~> 5.1.0', :require => 'friendly_id'
ruby '2.4.3'

Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
```

It looks like it's finding Rails 4.2 somewhere, and It breaks because of this, but I can't find where/why.
Is there any problem with the 5.2 rails version?
Thanks for help,

C.

**Comment by louishoang** [comment]
@chrisnopa After generating the friendly configuration file using`rails generate friendly_id`, there is a migration file that looks similar to this `db/migrate/2018xxxxx_create_friendly_id_slugs.rb`.

At the beginning of the file you will see `CreateFriendlyIdSlugs < ActiveRecord::Migration`, please replace it with `CreateFriendlyIdSlugs < ActiveRecord::Migration[5.2]`. It worked on my end.

**Comment by jcoyne** [comment]
Duplicate of #805
