### ISSUE TITLE
Friendly_Id is confusing assets with the slug link for the model

### ISSUE THREAD

**Issue by RailsCod3rFuture** [norman/friendly_id#872]
I'm having a weird issue where friendly_id is looking for assets like png images, instead of focusing on the model attribute that its used for. My server is unable to locate images and other resources because the friendly finder is looking for a slug to match the asset.

How can I fix this issue?

```
Started GET "/employers/business_executive_login.png" for 127.0.0.1 at 2018-06-11 20:03:36 -0400
Processing by EmployersController#show as PNG
  Parameters: {"id"=>"business_executive_login"}
  Employer Load (1.0ms)  SELECT  "employers".* FROM "employers" WHERE "employers"."slug" = $1 LIMIT $2  [["slug", "business_executive_login"], ["LIMIT", 1]]
Completed 404 Not Found in 6ms (ActiveRecord: 1.0ms)


  
ActiveRecord::RecordNotFound (can't find record with friendly id: "business_executive_login"):
  
app/controllers/employers_controller.rb:22:in `set_employer'
```

**Comment by parndt** [comment]
I think the problem is in your `routes.rb` file according to this line:
```
Processing by EmployersController#show as PNG
```

This means that you're routing to your controller's show action for routes matching `/employers/*`
