### ISSUE TITLE
ActiveRecord::RecordNotFound attributes are not passed

### ISSUE THREAD

**Issue by sPaCeMoNk3yIam** [norman/friendly_id#880]
https://github.com/norman/friendly_id/blob/e8186c6d407ba63ac6edfeff251c7355f8e212dc/lib/friendly_id/finder_methods.rb#L23
https://github.com/norman/friendly_id/blob/e8186c6d407ba63ac6edfeff251c7355f8e212dc/lib/friendly_id/finder_methods.rb#L37
https://api.rubyonrails.org/classes/ActiveRecord/RecordNotFound.html

FriendlyId should pass all attributes (`model`, `primary_key`, `id`) correctly to ensure consistent behavior for error handling. With `id`, of course, being the `friendly_id`.

**Comment by parndt** [comment]
Fixed by #890
