### ISSUE TITLE
History module doesn't work in rails 5.2

### ISSUE THREAD

**Issue by patrickoramah** [norman/friendly_id#883]
I'm using friendly_id ~> 5.2 gem but each time i try to use the history module the program breaks and give this error ![error ](https://i.imgur.com/85HJ6Ni.jpg) anyone else having this issue?

**Comment by kevinhq** [comment]
Have different error, but it also happened if `history` is used. Rails 5.2.2 with friendly_id 5.2.4

`ActiveRecord::NotNullViolation: Mysql2::Error: Field 'slug' doesn't have a default value: INSERT INTO `friendly_id_slugs` (`sluggable_id`, `sluggable_type`, `created_at`) VALUES (10, 'Concept', '2018-12-20 08:35:49')`

Any idea?

**Comment by olivierlacan** [comment]
Is this issue still occurring for you all?

**Comment by LanceH** [comment]
I was still getting the postgres error when using uuid's.  Fortunately I could change the friendly_id_slugs table to use :uuid for sluggable_ids since all my ids are :uuid.
