### ISSUE TITLE
"Undefined method slug" even after migrating

### ISSUE THREAD

**Issue by Dreamersoul** [norman/friendly_id#886]
i realize that multiple people posted this already, i am posting this issue to propose a solution.
if this is indeed an issue then i don't mind tackling it and posting a PR. however if we need to add the slug column i suggest we update the readme.md to include that information.

thank you for this amazing tool

**Comment by pkayokay** [comment]
@Dreamersoul have you been able to resolve it by adding a slug column?

**Comment by Dreamersoul** [comment]
Yeah! My suggestion is to add that step into the readme file!
