### ISSUE TITLE
Ability to turn off the routing helper

### ISSUE THREAD

**Issue by mikelarkin** [norman/friendly_id#888]
I notice that in the source there's a config option for `config.routes = :friendly` but it doesn't seem to let me turn this off.

Is this possible?  I don't want my entire app to use slugs for all the routes (we have admin routes and other internal ones) but only in one place.  So rather than go through and find every location I did `some_url(model)` and change it to `some_url(model.id)` it'd be nicer to say "Hey, don't override the routing helper please"

Maybe I'm just missing something but when I do any of the following

```
FriendlyId.defaults do |config|

config.routes = false
config.routes false
config.routes nil
config.routes = :normal
config.routes = :rails


```
I get tons of errors elsewhere.

**Comment by mridulap2003** [comment]
I believe you can change the route generation to default on a per-model basis. See [this pull request](https://github.com/norman/friendly_id/pull/735) (released in [5.2.0](https://github.com/norman/friendly_id/pull/735)).
