### ISSUE TITLE
`%2` Added to Slug Before the Organization Name

### ISSUE THREAD

**Issue by iarobinson** [norman/friendly_id#895]
Great work with this project Norman + team. Here's what I'm trying to fix:

Version information for FriendlyId, Rails and Ruby.
friendly_id', '~> 5.2.4'
Rails 5.2.2
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]

Full stack trace and error message (if you have them).
Any snippets of relevant model, view or controller code that shows how you are using FriendlyId.

Here is the URL that is being generated:

`http://localhost:3000/organizations/%2Fthompson-xray` 

The `%2` is not wanted.

**Comment by parndt** [comment]
With URL encoding, %2f means / so maybe the resource has a / at the start of it? Can you show the contents of that database row @iarobinson ?

**Comment by iarobinson** [comment]
@parndt Thank you. Here it is:

<img width="693" alt="screen shot 2019-02-16 at 6 04 28 pm" src="https://user-images.githubusercontent.com/7991933/52907368-57305c80-3215-11e9-899a-5a5c73203642.png">

**Comment by parndt** [comment]
@iarobinson no problem, glad you got it sorted! :+1:
