### ISSUE TITLE
Use only slugs in URL

### ISSUE THREAD

**Issue by mridulnagpal** [norman/friendly_id#901]
I want to block the urls with id param and only use unique slugs to avoid data scraping. Something like `/show/:id` does not work whereas `/show/:slug` should work where slug is unique

**Comment by rokumatsumoto** [comment]
I assume you don't use UUID for your primary keys.
You can use [constraints](https://guides.rubyonrails.org/routing.html#specifying-constraints ) for your resources and redirect to root if constraint violation happens.

**routes.rb**
```
  resources :articles, constraints: { id: /.*\D+.*/ } do
    resources :comments
  end

  get '*path' => redirect('/')
```

**Test strings:**
Allows:
- 3d
- 3d-model
- model
- model-3d

Denies
- 3

Test regex
https://rubular.com/r/UQj8orYqBBsqwn
