### ISSUE TITLE
slug being unset if model has any errors (unset_slug_if_invalid)

### ISSUE THREAD

**Issue by Ancez** [norman/friendly_id#902]
When running a .save() method on a model which has errors on other fields (e.g.` name` is invalid), the `slug` gets set to nil but was valid. It should preserve the value after .save() on the model so the user can fix the remaining errors without having to rewrite the slug. This also leads to other errors on the slug field that may have caused the model to fail validation to be removed.

method `unset_slug_if_invalid` shouldn't be checking for `errors.present?`. Instead it should only check that the `slug` field has any errors (doing `errors[friendly_id_config.query_field].present?` solves the problem)

```ruby
  def unset_slug_if_invalid
    if errors[friendly_id_config.query_field].present? && attribute_changed?(friendly_id_config.query_field.to_s)
      diff = changes[friendly_id_config.query_field]
      send "#{friendly_id_config.slug_column}=", diff.first
    end
   end
```

**Comment by parndt** [comment]
Hi @Ancez thanks for this; could you please open a pull request with this change so we can run tests against it?

**Comment by Ancez** [comment]
Hi @parndt, thank you for your reply, I've created a PR with this code change but some of the specs will need updating. This issue might not be visible when running the specs but it will become quite blunt once testing it on the website

**Comment by parndt** [comment]
cool, keen to see what you come up with, hopefully avoiding a breaking change.
