### ISSUE TITLE
Receiving Error On Heroku Production: no method error

### ISSUE THREAD

**Issue by monroemann** [norman/friendly_id#905]
Hi All!  This is an odd error.  We are using the friendly_id gem, and everything works perfectly on development.  When you create a user, a slug is created as first_namelast_name, i.e. www.breakdiving.io/monroemann  (not a working link).

However, we just launched to production, and now users are unable to complete the signup.  This is the error on sentry:

https://gyazo.com/48dd51778ca178bf94f0472fa6a0c0cb

And here is our relevant code:

https://gyazo.com/3ed075d407a47b072498f3a0abeaf8a1

Any reason why we are getting this error only on development?  Thank you for any guidance!

**Comment by bhavyabh** [comment]
We appreciate any help you provide. Thank you.

**Comment by parndt** [comment]
Have you run the database migrations?
