### ISSUE TITLE
New release to support Rails 6

### ISSUE THREAD

**Issue by composerinteralia** [norman/friendly_id#917]
Thanks for the gem!

When you have a chance, it would nice to have an official release with https://github.com/norman/friendly_id/commit/cdd5971f91c40e0c05e5afb498d2ec1b452ffb44#diff-6c1e3429bcf1206c1a79aa1d516ada34R79 so we can use the finder methods with Rails 6.

In the meantime, we can use the `master` branch.

**Comment by olivierlacan** [comment]
@parndt Any chance you could do this please? Let me know if you need help with this.

**Comment by parndt** [comment]
@olivierlacan sure can, thanks for the prompt :+1:

**Comment by parndt** [comment]
> Successfully registered gem: friendly_id (5.3.0)

:heart: :purple_heart: :green_heart: :blue_heart:
