### ISSUE TITLE
finders doesn't work with Rails 6

### ISSUE THREAD

**Issue by joeradtke** [norman/friendly_id#918]
finders doesn't work with Rails 6

**Comment by goelinsights** [comment]
I believe this duplicates #917. Finders in rails 6 taken out by an if statement on ActiveRecord version

**Comment by olivierlacan** [comment]
To further document this, I have two models (Rails 6).

This one doesn't work with finders: 

```ruby
friendly_id do |config|
    config.base = :title
    config.use(:slugged, :finders)
    config.slug_column = :slug
  end
```

This one does work: 

```ruby
friendly_id do |config|
    config.base = :title
    config.use(:slugged, :finders, :scoped)
    config.scope = [:slug, :project_id]
    config.slug_column = :slug
  end
```

So it would appear that `:scoped` is causing finders to function in Rails 6.

**Comment by daniel-g** [comment]
:finders weren't working for me... so for anyone still struggling with this, this was my fix.

Change:

```ruby
Event.find(...)
```

to:

```ruby
Event.all.find(...)
```

it woks with any scope, include, etc. So it will also work if you have this:

```ruby
Event.includes(...).find(...)
```
