### ISSUE TITLE
Using full stop in slugs?

### ISSUE THREAD

**Issue by iraszl** [norman/friendly_id#920]
I need to add `.html` to the end of the slug, but it looks like a full stop is being escaped and replaced with a dash. Is there a way to override this behaviour?

_I'm adding this question here, because maybe the ability to add extensions is a feature idea?_

**Comment by parndt** [comment]
Does overriding `normalize_friendly_id` achieve what you're after @iraszl ? https://github.com/norman/friendly_id/blob/9cd4ce2b5d0425aa704872e1334b442cab03c29c/lib/friendly_id/slugged.rb#L254-L281

**Comment by iraszl** [comment]
@parndt Yes, thank you ! It totally does work, but it breaks the finding of pages because ruby thinks `.html` is a method, not just part of the string.

**Comment by parndt** [comment]
Ah, well there you will need to add support to the Rails routes file for `:format`, but this is out of scope for FriendlyId. Good luck!
