### ISSUE TITLE
Issue when there is `.`  character in name field

### ISSUE THREAD

**Issue by userrails** [norman/friendly_id#921]
if my `name` column is storing value like `John doe.`, then the friendly id generated is `john-doe.`

and url looks something like: `/post/john-doe.`

In rails

```ruby
id = params[:id]
=> john-doe
```

if you see, id variable is containing `john-doe` and ignoring `.` character, as it is reserved character in URL. And rails returning `No result found` in this case.

**Comment by parndt** [comment]
I was going to add a test case for this, but when I did so, I got a passing test:

```ruby
  test "slug should not retain fullstops" do
    transaction do
      journalist = Journalist.create name: 'Clark Kent.', active: true
      assert_equal 'clark-kent', journalist.slug, "value of slug should not have a fullstop"
    end
  end
```

Can you please share your friendly_id config?
