### ISSUE TITLE
Rails 6 ActiveRecord::RecordNotFound (can't find record with friendly id: "4-test-title"):

### ISSUE THREAD

**Issue by mices** [norman/friendly_id#933]
I'm using this with my BlogPost model
blog_post.rb:

    extend FriendlyId
      friendly_id :title, use: :slugged
      include ::ActionView::Helpers::TextHelper

blog_posts_controller.rb:

    @blog_post = BlogPost.friendly.find(params[:id])

error:

>ActiveRecord::RecordNotFound (can't find record with friendly id: "4-test-title"):

Over at rubygems.org I found that even with friendly_id 5.3.0 very old versions of minitest and mocha are required making this gem incompatible even with previous vesions of rails

minitest ~> 5.3
mocha ~> 1.1

**Comment by parndt** [comment]
![2D0595BE-4D55-4C87-A6AF-CBE58883F3FD](https://user-images.githubusercontent.com/10128/73102530-ea5e3000-3f56-11ea-85e0-c2906233f83f.jpeg)

The only runtime dependency is activerecord >= 4 - the others are development dependencies which aren't installed unless you're developing the library itself. 

Why are you including a view helper in your model?

**Comment by parndt** [comment]
In your example where is params[:id] coming from? Why is it 4-test-title instead of test-title ?
