### ISSUE TITLE
`find` for multiple slugs doesn't work

### ISSUE THREAD

**Issue by shir** [norman/friendly_id#935]
I have a record that uses `slug` as friendly id. I may find multiple records via:
```rb
Record.find([id1, id2]) # returns records.
```

Finding a record by single slug works as expected too:
```rb
Record.friendly.find(slug1) # returns a record.
```

But finding by multiple slugs doesn't work:
```rb
Record.friendly.find([slug1, slug2]) # raises `ActiveRecord::RecordNotFound`.
```

Actually, I don't see any other way to find multiple records by multiple mixed slugs and ids.

**Comment by parndt** [comment]
According to the code, we only ever look for a single record by its friendly ID. If there's more than one specified, we just escalate it to Active Record.

If you have a solid use case for wanting this functionality, would you be keen to investigate adding it please?
