### ISSUE TITLE
Scoped#should_generate_new_friendly_id? should only be true for persisted records

### ISSUE THREAD

**Issue by prateekkish** [norman/friendly_id#941]
Ever since the release where we got this "generate new friendly id whenever scope changes" feature, we have lost the ability to save an object with predefined scope column value.

This causes an override of the should_generate_new_friendly_id? method in every model that suffers from this.

Looks like someone worked on this https://github.com/norman/friendly_id/pull/931 but it's stale now.

Any thoughts @norman ?

**Comment by beauraF** [comment]
I worked on this a few months ago, and I've been using this fix in production since. I. have to write some test on my pull request. But I'm running out of time and it doesn't seem that easy :(

**Comment by bogdanRada** [comment]
Honestly i don't think its a good idea to generate new slugs only for persistent records. 
If you really want that you can do this in that model, otherwise other's people code that rely upon generating slugs even for new records, will be broken .  

```
 def should_generate_new_friendly_id?
    !new_record? && super
  end
```

**Comment by parndt** [comment]
That's good advice @bogdanRada !
