### ISSUE TITLE
New Release.

### ISSUE THREAD

**Issue by cduez** [norman/friendly_id#945]
Hello guys,

I was wondering if you would consider pushing a new release as the last one was in Sep 24, 2019 and there is few commits on master. 

Especially this one: https://github.com/norman/friendly_id/commit/fab2b7890a0d1c68e511bd427b37dd1b85757e97 which removes the deprecation warning for ruby 2.7 which I am really interested in :)

Thanks!

**Comment by cduez** [comment]
any chance you could take a look at this @parndt ?

**Comment by parndt** [comment]
Yeah @cduez, sure :smile: my normal system is being repaired at the moment, so please remind me if I still haven't done this next week.

**Comment by westonganger** [comment]
Reminder

**Comment by parndt** [comment]
Thank you very much @westonganger

**Comment by parndt** [comment]
Version 5.4.0 released !
