### ISSUE TITLE
Access the slug history for a record

### ISSUE THREAD

**Issue by oyeanuj** [norman/friendly_id#946]
Hey @parndt, quick question, and apologies if this is already somewhere in the docs and I might have missed. I'm using the `history` module with the library. I'm wondering if there is a way to get all the previous slug history for a record?

thank you!

**Comment by parndt** [comment]
@oyeanuj I haven't ever used this module, but it looks like you might be able to use a method like [slug_table_record](https://github.com/norman/friendly_id/blob/746138d5408067b3320eb0f823a18edc0592b630/lib/friendly_id/history.rb#L98-L100) but without the `.first` at the end.

This could probably helpfully be refactored to something like this:

```ruby
def slug_table_record(id)
  slug_table_records(id).first
end

def slug_table_records(id)
  select(quoted_table_name + '.*')
    .joins(:slugs)
    .where(slug_history_clause(id))
    .order(Slug.arel_table[:id].desc)
end
```
