### ISSUE TITLE
Unexpected :slug error on valid, unpersisted model

### ISSUE THREAD

**Issue by danielmklein** [norman/friendly_id#949]
While testing friendly_id 5.4.0, we are seeing something that is odd (I think -- I may be misunderstanding).

After constructing (but not saving) an instance (let's call it `my_instance`) of a given MyModel that uses `friendly_id :some_method, use: [:slugged, :finders]`, we see that while `my_instance.valid?` is `true`, `my_instance.errors.messages` is `{:slug=>[]}`.

Is this intentional? I find it rather peculiar, but I cannot pretend to be an expert here or fully understand what's going on under the hood with friendly_id. I am happy to flesh out this example if desired -- just let me know what extra info, if any, would be helpful!

**Comment by wbotelhos** [comment]
Yes @danielfone , I was going to open an issue just now.

A lot of specs broken since i used to match `errors.messages`. Using version `5.3.0` it works fine.

```
# frozen_string_literal: true

class Level < ApplicationRecord
  include FriendlyId

  friendly_id :name, use: %i[scoped slugged], scope: :course_id
end
```

```
RSpec.describe Level do
  let!(:record) { described_class.new(name: 'Name') }

  it 'validates' do
    expect(record.valid?).to be(true)

    record.save

    expect(record.errors.messages).to eq({})
  end
end
```

```
expected: {}
     got: {:slug=>[]}
```

**Comment by parndt** [comment]
Ah, this is unintentional

**Comment by vipulnsward** [comment]
This is a side-effect of Rails behavior(newly added due to https://github.com/norman/friendly_id/pull/938/files):

https://github.com/rails/rails/issues/23468#issuecomment-179868835

The access of the key value in the PR is causing extra erroneous hash key. 

The behavior should go away though on 5.2 Rails probably - https://github.com/rails/rails/pull/28584

P.S: Came here from our own failing specs in our Rails project.

**Comment by parndt** [comment]
Which versions of Rails are people having this issue with?

**Comment by danielmklein** [comment]
@parndt we are on Rails 6.0.3.2

**Comment by wbotelhos** [comment]
@parndt Rails 6.0.3.2

**Comment by parndt** [comment]
Thanks, that's useful

**Comment by parndt** [comment]
@wbotelhos @danielmklein @vipulnsward does the change in #952 solve the issue for you?

**Comment by danielmklein** [comment]
@parndt it looks like that PR does resolve this issue for us!

**Comment by StefSchenkelaars** [comment]
@parndt Would it be possible to create a new release (5.5.0?) which includes this fix?

**Comment by parndt** [comment]
@StefSchenkelaars yes, it is possible. Can you confirm for me please that using a git source against the master branch solves the problem in your app too?

**Comment by wbotelhos** [comment]
Hi @parndt , master fix this issue. Thank you! :)

**Comment by parndt** [comment]
Pushed a patch [version 5.4.1](https://rubygems.org/gems/friendly_id/versions/5.4.1) with this fix
