### ISSUE TITLE
Friendly_id path links won't work in Heroku.

### ISSUE THREAD

**Issue by amourali7135** [norman/friendly_id#955]
Hey all, I have an issue on my links that use friendly_id in Heroku.  In development, I originally had this line and it was working fine:  
```erb
<%= link_to 'See more of this creator', artist_path(artist.friendly_id), class: 'btn btn-primary'  %>
```
When I pushed it to Heroku though, it didn't work because of this error:  
```
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"artists", :id=>nil}, missing required keys: [:id]):
```
I've been experimenting around to get it to work, but I haven't been able to get anything working in production.  I tried some other ones that will work in development, but they both give me the same exact error in Heroku as before:  
```erb
<%= link_to 'See more of this creator', artist_path(id = artist.friendly_id), class: 'btn btn-primary'  %>

<%= link_to 'See more of this creator', artist_path(artist.id = artist.friendly_id), class: 'btn btn-primary'  %>
```
Any ideas on what I should do?

**Comment by parndt** [comment]
Try this one:
```erb
<%= link_to 'See more of this creator', artist_path(artist), class: 'btn btn-primary' %>
```

Alternatively:
```erb
<%= link_to 'See more of this creator', artist_path(artist.id), class: 'btn btn-primary' %>
```

**Comment by amourali7135** [comment]
Hello there.  Oh wow, the first one worked perfectly.  Thank you so much!
