### ISSUE TITLE
undefined method `relation' for class `#<Class:Sluggable>'

### ISSUE THREAD

**Issue by saqib1324** [norman/friendly_id#958]
App works great locally. When I push to Heroku, app crashes and I get this error

`/app/vendor/bundle/ruby/2.6.0/gems/friendly_id-5.1.0/lib/friendly_id.rb:91:in 'singleton class': undefined method 'relation' for class #<Class:Sluggable>' (NameError)
Did you mean?  Rational`

**Comment by parndt** [comment]
do you get the same when you run it in `RAILS_ENV=production` locally?
