### ISSUE TITLE
Add a method to return a hash of relationship friendly_ids?

### ISSUE THREAD

**Issue by aximuseng** [norman/friendly_id#964]
I am using https://github.com/jsonapi-serializer/jsonapi-serializer for an API in my app.  I want to use my Friendly IDs to hide the actual DB id.

In the json gem you can call a custom method to get the ids of the relationship.  It's an extension of something like this:

```
class MyModel
  has_many :tasks
end

pry>MyModel.last.task_ids
=> [32475, 32471, 32472, 32473, 32474]
```

It looks to me that there is no Friendly id equivalent like:

```
pry>MyModel.last.friendly_task_ids
=> ['task-32475', 'task-32471', 'task-32472', 'task-32473', 'task-32474']

```

Does this exist in the existing code somewhere?

If not is there an appetite to add this?

I can add these custom methods in all my models but having this built in to Friendly ID would be better.

It seems as 'easy' as adding:

`relationship_name.pluck(:slug_column_name)`

**Comment by parndt** [comment]
> Does this exist in the existing code somewhere?
>
> If not is there an appetite to add this?

No, we try to keep the maintenance overhead as low as possible so I don't think this is something we want to support. Thanks for checking!

**Comment by aximuseng** [comment]
No worries - figured I would ask first.  I think I may just roll my own Module etc to add this where needed.  Right now I am just adding these manually.
