### ISSUE TITLE
slug not change after updating records 

### ISSUE THREAD

**Issue by scratchoo** [norman/friendly_id#968]
The documentation says:

**As of FriendlyId 5.0, slugs are only generated when the slug field is nil. If you want a slug to be regenerated,set the slug field to nil**

Before update if  we do:

```
def update
  
    @post.slug = nil
   
     respond_to do |format|
      if @post.update(post_params)
        # ....
      end
    end
end
```
the slug doesn't get updated with the new value, instead it takes the previous slug value, 

for example if the title attribute is "hello world" and we change it to "hello everyone", the slug becomes "hello-world"

if we change it again to "hello bird", the slug becomes "hello-everyone"

I tried to add this as well:

```
def should_generate_new_friendly_id?
    title_changed?
  end
```

But same behavior wither I use one of them, or both

I spent too much time searching before posting here, I hope someone gonna answer this issue :)

**Comment by moroz** [comment]
To anyone who stumbles on this issue: use `before_validate` instead of `before_update`
