### ISSUE TITLE
Suggestion: Remove stopwords from slugs

### ISSUE THREAD

**Issue by jayzalowitz** [norman/friendly_id#973]
stop_words = /\b('a|an|and|at|but|by|for|in|nor|of|on|or|so|the|to|up|yet')\b/
return "#{slug}".gsub! stop_words, ""

Should help with seo.

**Comment by parndt** [comment]
Thanks - you can do this now if you use the custom method approach as detailed here in the guide: https://norman.github.io/friendly_id/file.Guide.html#Column_or_Method_ 😄
