### ISSUE TITLE
Slug separator not working

### ISSUE THREAD

**Issue by chrism** [norman/friendly_id#979]
I've added to `config/initializers/friendly_id.rb` the two lines

```ruby
config.use :slugged
config.sequence_separator = '_'
```

And even tried including in my models

```ruby
  extend FriendlyId
  friendly_id :name, use: :slugged, sequence_separator: "_"
```

But no matter what, if I create a new model the slug is still parameterized with a hyphen.

```
Model.create(name:'with separator')
#<Model id: 1, name: "with separator", slug: "with-separator">
```

I've read similar issues like https://github.com/norman/friendly_id/issues/650 which has now been closed, but still have not been able to get this to work and tried everything suggested.

**Comment by k3vout** [comment]
Check this solution: https://stackoverflow.com/a/30323207/23497576
