### ISSUE TITLE
Heredoc with tilde `<<~` in the `.gemspec` is incompatible with older ruby versions

### ISSUE THREAD

**Issue by Bastes** [norman/friendly_id#987]
Hi, my team has the displeasure of working on an older ruby version (`2.2.3`) which does not understand all these fancy new tilde heredocs `<<~`, and that leads to this gem failing to install because the `.gemspec` contains the dreaded syntax ; since the `.gemspec` claims tolerating ruby as old as `2.1.0`, maybe it'd be better to use the older dash heredoc `<<-` or to bump up the requirements to ruby `2.3.0` where that syntax was born?

What do you think?

EDIT: After inspecting the code it appears the only use of the `<<~` is in the `.gemspec`, so I would suggest using the pre-existing `<<-` syntax rather than bump up the ruby version requirement.

**Comment by parndt** [comment]
@Bastes thanks - would you have any time or inclination to open a pull request that does exactly this please? 😄

**Comment by Bastes** [comment]
@parndt will do asap :)
